// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnDHwkO54HkITMVdpJf2ev7NY5mRzCMaM',
    appId: '1:50267147295:web:c9733d13feddfb7822192a',
    messagingSenderId: '50267147295',
    projectId: 'pick-and-ride-a7067',
    authDomain: 'pick-and-ride-a7067.firebaseapp.com',
    databaseURL: 'https://pick-and-ride-a7067-default-rtdb.firebaseio.com',
    storageBucket: 'pick-and-ride-a7067.appspot.com',
    measurementId: 'G-LSDH24Q4PC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzXKqvbm5CLjx8TbABTznw4r3KyJ9p-E',
    appId: '1:50267147295:android:0e61ea2b05db350822192a',
    messagingSenderId: '50267147295',
    projectId: 'pick-and-ride-a7067',
    databaseURL: 'https://pick-and-ride-a7067-default-rtdb.firebaseio.com',
    storageBucket: 'pick-and-ride-a7067.appspot.com',
  );

}