
import 'package:get/get_navigation/src/root/internacionalization.dart';

class LocalString extends Translations {

  @override
  Map<String,Map<String,String>> get keys => {
    'en_US': {
      "Financing fell through" :  "Financing fell through",
      "Inspection issues" : "Inspection issues",
      "Change in financial situation" : "Change in financial situation",
      "Title issues" : "Title issues",
      "Seller changes their mind" : "Seller changes their mind",
      "Competing offer" : "Competing offer",
      "Personal reasons" : "Personal reasons",
      "Others" : "Others",
      "Cancel Booking" : "Cancel Booking",
      "Select Reason" : "Select Reason",
      "Please select the reasone for cancellation:" : "Please select the reasone for cancellation:",
      "Please enter the different Boarding & Drop Point" : "Please enter the different Boarding & Drop Point",
      "No booking found" : "No booking found",
      "You don't have any booking records!" : "You don't have any booking records!",
      "You don't have any previous records!" : "You don't have any previous records!",
      "Amenities" : "Amenities",
      "Review" : "Review",
      "Download App" : "Download App",
      "Language" : "Language",
      "Account Number" : "Account Number",
      "Back" : "Back",

      "Seamless Travel Simplified" : "Seamless Travel Simplified",
      "Recent Booking" : "Recent Booking",
      "PROCEED" : "PROCEED",
      "Overview" : "Overview",
      "Quick links" : "Quick links",
      "Utilitises" : "Utilitises",
      "Blog" : "Blog",
      "Style guide" : "Style guide",
      "Company" : "Company",
      "Contact" : "Contact",
      "Licensing" : "Licensing",
      "Pricing" : "Pricing",
      "Changelog" : "Changelog",
      "Subcribe to our newsletter" : "Subcribe to our newsletter",
      "Enter youe Email" : "Enter youe Email",
      "Refer and Earn" : "Refer and Earn",
      "Sign Up on Zigzag" : "Sign Up on Zigzag",
      "Go Home" : "Go Home",
      "Ticket ID" : "Ticket ID",
      "Please enter the amount less then 10." : "Please enter the amount less then 10.",
      "Rafer a Friend" : "Rafer a Friend",
      "Earn" : "Earn",
      "for each friend you refer" : "for each friend you refer",
      "Price - Low to high" : "Price - Low to high",
      "Best rated first" : "Best rated first",
      "Early departure" : "Early departure",
      "Late departure" : "Late departure",
      "NONAC" : "NONAC",
      "Sleeper" : "Sleeper",
      "Seater" : "Seater",
      "Booked" : "Booked",
      "Female Booked" : "Female Booked",
      "Selected" : "Selected",
      "Empty" : "Empty",
      "Drop Point" : "Drop Point",
      "Email Id" : "Email Id",
      "Enter Your Name" : "Enter Your Name",
      "Enter Age" : "Enter Age",
      "Enter Full Name" : "Enter Full Name",
      "Total Payment" : "Total Payment",
      "Booking Confirmed!" : "Booking Confirmed!",
      "Home" : "Home",
      "My Wallet" : "My Wallet",
      "My Earning" : "My Earning",
      "Wallet" : "Wallet",
      "TOTAL EARNING BALANCE" : "TOTAL EARNING BALANCE",
      "Withdraw" : "Withdraw",
      "Transaction Details" : "Transaction Details",
      "Payout Id" : "Payout Id",
      "Amount" : "Amount",
      "Pay by" : "Pay by",
      "Request Date" : "Request Date",
      "Payout Request" : "Payout Request",
      "Minimum amount" : "Minimum amount",
      "Enter Amount" : "Enter Amount",
      "Select Type" : "Select Type",
      "Bank Name" : "Bank Name",
      "Account Holder Name" : "Account Holder Name",
      "Cancel" : "Cancel",
      "Proceed" : "Proceed",
      "Enjoy the travel experience with us" : "Enjoy the travel experience with us",
      "Book your adventure, pack your bags and let the exploration begin." : "Book your adventure, pack your bags and let the exploration begin.",
      "Online Bus Ticket Booking" : "Online Bus Ticket Booking",
      "Embark on a seamless travel  experience with ProZigzagBus" : "Embark on a seamless travel  experience with ProZigzagBus",
      "Book Now" : "Book Now",
      "My Ticket" : "My Ticket",
      "Upcoming Trips" : "Upcoming Trips",
      "Completed Trips" : "Completed Trips",
      "Cancel Trips" : "Cancel Trips",
      "Cancellation Policy" : "Cancellation Policy",
      "Contact Us" : "Contact Us",
      "Term & Condition" : "Term & Condition",
      "Privacy Policy" : "Privacy Policy",
      "My Profile" : "My Profile",
      "Phone Number" : "Phone Number",
      "Enter Password" : "Enter Password",
      "Enter Name" : "Enter Name",
      "Confirm" : "Confirm",
      "From City" : "From City",
      "To City" : "To City",
      "Date" : "Date",
      "Please enter the Boarding / Drop Point" : "Please enter the Boarding / Drop Point",
      "Search" : "Search",
      "Ticket Details" : "Ticket Details",
      "Download Ticket" : "Download Ticket",
      "Download Your Ticket !" : "Download Your Ticket !",
      "Download PDF" : "Download PDF",
      "Back to Home" : "Back to Home",
      "Enter your Feedback" : "Enter your Feedback",
      "Non AC" : "Non AC",
      "AC" : "AC",
      "Booking Date" : "Booking Date",
      "Payment Method" : "Payment Method",
      "Transaction Id" : "Transaction Id",
      "Ticket Id" : "Ticket Id",
      "Passanger(S)" : "Passanger(S)",
      "Age" : "Age",
      "Seat" : "Seat",
      "Contact Details" : "Contact Details",
      "Driver Details" : "Driver Details",
      "Bus Number" : "Bus Number",
      "Price Details" : "Price Details",
      "Price" : "Price",
      "Tax" : "Tax",
      "Discount" : "Discount",
      "Total Price" : "Total Price",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time.",
      "TOTAL WALLET BALANCE" : "TOTAL WALLET BALANCE",
      "Top Up" : "Top Up",
      "Enter Wallet Amount" : "Enter Wallet Amount",
      "Select Payment Method" : "Select Payment Method",
      "Continue" : "Continue",
      "Top up" : "Top up",
      "Successfuly" : "Successfuly",
      "has been added to your wallet" : "has been added to your wallet",
      "Done For Now" : "Done For Now",
      "Another Top Up" : "Another Top Up",
      "Change Password" : "Change Password",
      "Enter your Mobile" : "Enter your Mobile",
      "Next" : "Next",
      "Something Went Wrong!" : "Something Went Wrong!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab.",
      "View Transaction" : "View Transaction",
      "Boarding Point" : "Boarding Point",
      "Booked by Female passenger" : "Booked by Female passenger",
      "You can not add more than" : "You can not add more than",
      "passengers to a single booking with this operator" : "passengers to a single booking with this operator",
      "Seats" : "Seats",
      "Lower Seat -" : "Lower Seat -",
      "Upper Seat -" : "Upper Seat -",
      "Procced" : "Procced",
      "No data found!" : "No data found!",
      "Lower Berth" : "Lower Berth",
      "Upper Berth" : "Upper Berth",
      "Personal Info" : "Personal Info",
      "Dark Mode" : "Dark Mode",
      "Term & Conditions" : "Term & Conditions",
      "Services" : "Services",
      "Downloads" : "Downloads",
      "Scan Code" : "Scan Code",
      "Log in" : "Log in",
      "Sign up" : "Sign up",
      "Logout" : "Logout",
      "Passenger Details" : "Passenger Details",
      "Passanger" : "Passanger",
      "Seat 2" : "Seat 2",
      "Gender" : "Gender",
      "Name" : "Name",
      "Mobile Details" : "Mobile Details",
      "Enter Your Mobile Number" : "Enter Your Mobile Number",
      "Enter Your Email Id" : "Enter Your Email Id",
      "Amount : " : "Amount : ",
      "(Exclusive of Texes)" : "(Exclusive of Texes)",
      "Please fill all details" : "Please fill all details",
      "Please select gender" : "Please select gender",
      "Log In on Zigzag" : "Log In on Zigzag",
      "Forgot Password" : "Forgot Password",
      "Don't have an account yet? " : "Don't have an account yet? ",
      "SignUp" : "SignUp",
      "Something Went wrong!" : "Something Went wrong!",
      "Invalid Email/Mobile No or Password!!!" : "Invalid Email/Mobile No or Password!!!",
      "Mobile or Password went wrong!" : "Mobile or Password went wrong!",
      "Your Journey, Your Way" : "Your Journey, Your Way",
      "Book, Ride, Enjoy" : "Book, Ride, Enjoy",
      "Explore, One Bus at a Time" : "Explore, One Bus at a Time",
      "Customize your travel effortlessly." : "Customize your travel effortlessly.",
      "Easy booking and boarding for a stress-free journey." : "Easy booking and boarding for a stress-free journey.",
      "Swift booking and delightful bus rides." : "Swift booking and delightful bus rides.",
      "Discover new places, one bus ride after another." : "Discover new places, one bus ride after another.",
      "Qr Code" : "Qr Code",
      "Tansaction Details" : "Tansaction Details",
      "Full Name" : "Full Name",
      "Email" : "Email",
      "Search Bus" : "Search Bus",
      "Fill Details" : "Fill Details",
      "Payment & Other Details" : "Payment & Other Details",
      "Apply Coupon" : "Apply Coupon",
      "Coupon Applied!" : "Coupon Applied!",
      "Remove" : "Remove",
      "Pay from Wallet" : "Pay from Wallet",
      "Total Pay:-" : "Total Pay:-",
      "Valid Until" : "Valid Until",
      "Min Amount" : "Min Amount",
      "Apply" : "Apply",
      "User" : "User",
      "Agent" : "Agent",
      "Enter your Email" : "Enter your Email",
      "Enter your Name" : "Enter your Name",
      "Enter Referral Code (optional)" : "Enter Referral Code (optional)",
      "Sign Up" : "Sign Up",
      "Already have an account " : "Already have an account ",
      "Log In" : "Log In",
      "Morning" : "Morning",
      "Afternoon" : "Afternoon",
      "Evening" : "Evening",
      "Night" : "Night",
      "Wifi" : "Wifi",
      "Water Bottle" : "Water Bottle",
      "Charging Point" : "Charging Point",
      "Music" : "Music",
      "Medical Kit" : "Medical Kit",
      "Live Tracking" : "Live Tracking",
      "SEATER" : "SEATER",
      "SLEEPER" : "SLEEPER",
      "Zigzag fulfilled buses are not available at this time." : "Zigzag fulfilled buses are not available at this time.",
      "Sort By-" : "Sort By-",
      "Departure Time" : "Departure Time",
      "Arrival Time" : "Arrival Time",
      "Bus Type" : "Bus Type",
      "Bus Facilities" : "Bus Facilities",
      "Bus Operator" : "Bus Operator",
      "To" : "To",
      "From" : "From",
    },
    'gu_GUJARATI': {
      "Cancel Booking" : "બુકિંગ રદ કરો",
      "Select Reason" : "કારણ પસંદ કરો",
      "Please select the reasone for cancellation:" : "કૃપા કરીને રદ કરવા માટેનું કારણ પસંદ કરો:",
      "Please enter the different Boarding & Drop Point" : "કૃપા કરીને વિવિધ બોર્ડિંગ અને ડ્રોપ પોઈન્ટ દાખલ કરો",
      "No booking found" : "કોઈ બુકિંગ મળ્યું નથી",
      "You don't have any cancel booking records!" : "તમારી પાસે બુકિંગ રદ કરવાનો કોઈ રેકોર્ડ નથી!",
      "You don't have any booking records!" : "તમારી પાસે કોઈ બુકિંગ રેકોર્ડ નથી!",
      "You don't have any previous records!" : "તમારી પાસે કોઈ અગાઉના રેકોર્ડ્સ નથી!",
      "Review" : "સમીક્ષા",
      "Download App" : "એપ ડાઉનલોડ કરો",
      "Language" : "ભાષા",
      "Account Number" : "ખાતા નંબર",
      "Back" : "પાછળ",
      "Amenities" : "સુવિધાઓ",
      "Seamless Travel Simplified" : "અવિરત મુસાફરી સરળ",
      "Recent Booking" : "તાજેતરનું બુકિંગ",
      "PROCEED" : "આગળ વધો",
      "No Coupon Available!" : "કોઈ કૂપન ઉપલબ્ધ નથી!",
      "Overview" : "ઝાંખી",
      "Quick links" : "ઝડપી સંપર્ક",
      "Utilitises" : "ઉપયોગિતાઓ",
      "Blog" : "બ્લોગ",
      "Style guide" : "શૈલી માર્ગદર્શિકા",
      "Company" : "કંપની",
      "Contact" : "સંપર્ક કરો",
      "Licensing" : "લાઇસન્સિંગ",
      "Pricing" : "ભાવ",
      "Changelog" : "ચેન્જલોગ",
      "Subcribe to our newsletter" : "અમારા ન્યૂઝલેટર પર સબ્સ્ક્રાઇબ કરો",
      "Enter youe Email" : "તમારો ઈમેલ દાખલ કરો",
      "Refer and Earn" : "સંદર્ભ લો અને કમાઓ",
      "Sign Up on Zigzag" : "ઝિગઝેગ પર સાઇન અપ કરો",
      "Go Home" : "ઘર જાઓ",
      "Ticket ID" : "ટિકિટ ID",
      "Please enter the amount less then 10." : "કૃપા કરીને 10 કરતા ઓછી રકમ દાખલ કરો.",
      "Rafer a Friend" : "રેફર અ ફ્રેન્ડ",
      "Earn" : "કમાઓ",
      "for each friend you refer" : "તમે સંદર્ભિત દરેક મિત્ર માટે",
      "Price - Low to high" : "કિંમત - નીચી થી ઊંચી",
      "Best rated first" : "શ્રેષ્ઠ રેટિંગ પ્રથમ",
      "Early departure" : "વહેલું પ્રસ્થાન",
      "Late departure" : "મોડી પ્રસ્થાન",
      "NONAC" : "બિન એસી",
      "Sleeper" : "સ્લીપર",
      "Seater" : "સીટર",
      "Booked" : "બુક કરાવ્યું",
      "Female Booked" : "મહિલા બુક",
      "Selected" : "પસંદ કરેલ",
      "Empty" : "ખાલી",
      "Drop Point" : "ડ્રોપ પોઈન્ટ",
      "Email Id" : "ઈમેલ આઈડી",
      "Enter Your Name" : "તમારું નામ દાખલ કરો",
      "Enter Age" : "ઉંમર દાખલ કરો",
      "Enter Full Name" : "પૂરું નામ દાખલ કરો",
      "Total Payment" : "કુલ ચુકવણી",
      "Booking Confirmed!" : "બુકિંગ કન્ફર્મ!",
      "Home" : "ઘર",
      "My Wallet" : "મારું પાકીટ",
      "My Earning" : "મારી કમાણી",
      "Wallet" : "વૉલેટ",
      "TOTAL EARNING BALANCE" : "કુલ અર્નિંગ બેલેન્સ",
      "Withdraw" : "ઉપાડો",
      "Transaction Details" : "વ્યવહારની વિગતો",
      "Payout Id" : "પેઆઉટ આઈડી",
      "Amount" : "રકમ",
      "Pay by" : "દ્વારા ચૂકવણી કરો",
      "Request Date" : "વિનંતી તારીખ",
      "Payout Request" : "ચૂકવણીની વિનંતી",
      "Minimum amount" : "ન્યૂનતમ રકમ",
      "Enter Amount" : "રકમ દાખલ કરો",
      "Select Type" : "પ્રકાર પસંદ કરો",
      "Bank Name" : "બેંકનું નામ",
      "Account Holder Name" : "એકાઉન્ટ ધારકનું નામ",
      "Cancel" : "રદ કરો",
      "Proceed" : "આગળ વધો",
      "Enjoy the travel experience with us" : "અમારી સાથે મુસાફરીના અનુભવનો આનંદ માણો",
      "Book your adventure, pack your bags and let the exploration begin." : "તમારું સાહસ બુક કરો, તમારી બેગ પેક કરો અને શોધખોળ શરૂ કરવા દો.",
      "Online Bus Ticket Booking" : "ઓનલાઈન બસ ટિકિટ બુકિંગ",
      "Embark on a seamless travel  experience with ProZigzagBus" : "ProZigzagBus સાથે અવિરત  મુસાફરીનો અનુભવ શરૂ કરો",
      "Book Now" : "હવે બુક કરો",
      "My Ticket" : "મારી ટિકિટ",
      "Upcoming Trips" : "આગામી પ્રવાસો",
      "Completed Trips" : "પૂર્ણ કરેલ પ્રવાસો",
      "Cancel Trips" : "ટ્રિપ્સ રદ કરો",
      "Cancellation Policy" : "રદીકરણ નીતિ",
      "Contact Us" : "અમારો સંપર્ક કરો",
      "Term & Condition" : "ટર્મ એન્ડ કન્ડીશન",
      "Privacy Policy" : "ગોપનીયતા નીતિ",
      "My Profile" : "મારી પ્રોફાઈલ",
      "Phone Number" : "ફોન નંબર",
      "Enter Password" : "પાસવર્ડ દાખલ કરો",
      "Enter Name" : "નામ દાખલ કરો",
      "Confirm" : "પુષ્ટિ કરો",
      "From City" : "શહેરમાંથી",
      "To City" : "શહેરને",
      "Date" : "તારીખ",
      "Please enter the Boarding / Drop Point" : "કૃપા કરીને બોર્ડિંગ / ડ્રોપ પોઈન્ટ દાખલ કરો",
      "Search" : "શોધો",
      "Ticket Details" : "ટિકિટ વિગતો",
      "Download Ticket" : "ટિકિટ ડાઉનલોડ કરો",
      "Download Your Ticket !" : "તમારી ટિકિટ ડાઉનલોડ કરો!",
      "Download PDF" : "PDF ડાઉનલોડ કરો",
      "Back to Home" : "ઘરે પાછા",
      "Enter your Feedback" : "તમારો પ્રતિસાદ દાખલ કરો",
      "Non AC" : "નોન એસી",
      "AC" : "એસી",
      "Booking Date" : "બુકિંગ તારીખ",
      "Payment Method" : "ચુકવણી પદ્ધતિ",
      "Transaction Id" : "ટ્રાન્ઝેક્શન આઈડી",
      "Ticket Id" : "ટિકિટ આઈડી",
      "Passanger(S)" : "પેસેન્જર(ઓ)",
      "Age" : "ઉંમર",
      "Seat" : "બેઠક",
      "Contact Details" : "સંપર્ક વિગતો",
      "Driver Details" : "ડ્રાઇવરની વિગતો",
      "Bus Number" : "બસ નંબર",
      "Price Details" : "કિંમત વિગતો",
      "Price" : "કિંમત",
      "Tax" : "કર",
      "Discount" : "ડિસ્કાઉન્ટ",
      "Total Price" : "કુલ કિંમત",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "ડ્રાઇવરનો મોબાઇલ નંબર, નામ અને બસ નંબર તમારા નિર્ધારિત પ્રસ્થાનના સમયના એક કલાક પહેલા રજૂ કરવામાં આવશે.",
      "TOTAL WALLET BALANCE" : "કુલ વૉલેટ બેલેન્સ",
      "Top Up" : "ટોચ",
      "Enter Wallet Amount" : "વૉલેટની રકમ દાખલ કરો",
      "Select Payment Method" : "ચુકવણી પદ્ધતિ પસંદ કરો",
      "Continue" : "ચાલુ રાખો",
      "Top up" : "ટોચ",
      "Successfuly" : "સફળતાપૂર્વક",
      "has been added to your wallet" : "તમારા વૉલેટમાં ઉમેરવામાં આવ્યું છે",
      "Done For Now" : "હમણાં માટે થઈ ગયું",
      "Another Top Up" : "અન્ય ટોપ અપ",
      "Change Password" : "પાસવર્ડ બદલો",
      "Enter your Mobile" : "તમારો મોબાઈલ દાખલ કરો",
      "Next" : "આગળ",
      "Something Went Wrong!" : "કંઈક ખોટું થયું!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "અભિનંદન! તમારી બસ ટિકિટ કન્ફર્મ થઈ ગઈ છે. વધુ વિગતો માટે મારી બુકિંગ ટેબ તપાસો.",
      "View Transaction" : "વ્યવહાર જુઓ",
      "Boarding Point" : "બોર્ડિંગ પોઈન્ટ",
      "Booked by Female passenger" : "મહિલા મુસાફર દ્વારા બુક કરાવેલ",
      "You can not add more than" : "કરતાં વધુ ઉમેરી શકતા નથી",
      "passengers to a single booking with this operator" : "આ ઓપરેટર સાથે એક જ બુકિંગ માટે મુસાફરો",
      "Seats" : "બેઠકો",
      "Lower Seat -" : "નીચલી સીટ -",
      "Upper Seat -" : "ઉપરની સીટ -",
      "Procced" : "પ્રક્રિયા",
      "No data found!" : "કોઈ ડેટા મળ્યો નથી!",
      "Lower Berth" : "લોઅર બર્થ",
      "Upper Berth" : "અપર બર્થ",
      "Personal Info" : "વ્યક્તિગત માહિતી",
      "Dark Mode" : "ડાર્ક મોડ",
      "Term & Conditions" : "ટર્મ અને શરતો",
      "Services" : "સેવાઓ",
      "Downloads" : "ડાઉનલોડ્સ",
      "Scan Code" : "સ્કેન કોડ",
      "Log in" : "પ્રવેશ કરો",
      "Sign up" : "સાઇન અપ કરો",
      "Logout" : "લૉગ આઉટ",
      "Passenger Details" : "પેસેન્જર વિગતો",
      "Passanger" : "પેસેન્જર",
      "Seat 2" : "બેઠક 2",
      "Gender" : "જાતિ",
      "Name" : "નામ",
      "Mobile Details" : "મોબાઇલ વિગતો",
      "Enter Your Mobile Number" : "તમારો મોબાઈલ નંબર દાખલ કરો",
      "Enter Your Email Id" : "તમારું ઈમેલ આઈડી દાખલ કરો",
      "Amount : " : "રકમ :",
      "(Exclusive of Texes)" : "(Texes સિવાય)",
      "Please fill all details" : "કૃપા કરીને બધી વિગતો ભરો",
      "Please select gender" : "કૃપા કરીને લિંગ પસંદ કરો",
      "Log In on Zigzag" : "ઝિગઝેગ પર લોગ ઇન કરો",
      "Forgot Password" : "પાસવર્ડ ભૂલી ગયા છો",
      "Don't have an account yet? " : "હજુ સુધી એક એકાઉન્ટ નથી?",
      "SignUp" : "સાઇન અપ કરો",
      "Something Went wrong!" : "કંઈક ખોટું થયું!",
      "Invalid Email/Mobile No or Password!!!" : "અમાન્ય ઈમેલ/મોબાઈલ નંબર અથવા પાસવર્ડ!!!",
      "Mobile or Password went wrong!" : "મોબાઈલ કે પાસવર્ડ ખોટો પડ્યો!",
      "Your Journey, Your Way" : "તમારી જર્ની, તમારો રસ્તો",
      "Book, Ride, Enjoy" : "બુક કરો, રાઈડ કરો, એન્જોય કરો",
      "Explore, One Bus at a Time" : "અન્વેષણ કરો, એક સમયે એક બસ",
      "Customize your travel effortlessly." : "તમારી મુસાફરીને સરળતાથી કસ્ટમાઇઝ કરો.",
      "Easy booking and boarding for a stress-free journey." : "તણાવમુક્ત પ્રવાસ માટે સરળ બુકિંગ અને બોર્ડિંગ.",
      "Swift booking and delightful bus rides." : "સ્વિફ્ટ બુકિંગ અને આનંદદાયક બસ સવારી.",
      "Discover new places, one bus ride after another." : "નવા સ્થાનો શોધો, એક પછી એક બસની સવારી.",
      "Qr Code" : "Qr કોડ",
      "Tansaction Details" : "ટેનસેક્શન વિગતો",
      "Full Name" : "પૂરું નામ",
      "Email" : "ઈમેલ",
      "Search Bus" : "બસ શોધો",
      "Fill Details" : "વિગતો ભરો",
      "Payment & Other Details" : "ચુકવણી અને અન્ય વિગતો",
      "Apply Coupon" : "કૂપન લાગુ કરો",
      "Coupon Applied!" : "કૂપન લાગુ!",
      "Remove" : "દૂર કરો",
      "Pay from Wallet" : "વૉલેટમાંથી ચુકવણી કરો",
      "Total Pay:-" : "કુલ પગાર:-",
      "Valid Until" : "માન્ય છે ત્યાં સુધી",
      "Min Amount" : "ન્યૂનતમ રકમ",
      "Apply" : "અરજી કરો",
      "User" : "વપરાશકર્તા",
      "Agent" : "એજન્ટ",
      "Enter your Email" : "તમારું ઈમેલ એડ્રેસ લખો",
      "Enter your Name" : "તમારું નામ દાખલ કરો",
      "Enter Referral Code (optional)" : "રેફરલ કોડ દાખલ કરો (વૈકલ્પિક)",
      "Sign Up" : "સાઇન અપ કરો",
      "Already have an account " : "પહેલેથી જ એક એકાઉન્ટ છે",
      "Log In" : "પ્રવેશ કરો",
      "Morning" : "સવાર",
      "Afternoon" : "બપોર",
      "Evening" : "સાંજ",
      "Night" : "રાત્રિ",
      "Wifi" : "વાઇફાઇ",
      "Water Bottle" : "પાણીની બોટલ",
      "Charging Point" : "ચાર્જિંગ પોઈન્ટ",
      "Music" : "સંગીત",
      "Medical Kit" : "મેડિકલ કીટ",
      "Live Tracking" : "લાઈવ ટ્રેકિંગ",
      "SEATER" : "સીટર",
      "SLEEPER" : "સ્લીપર",
      "Zigzag fulfilled buses are not available at this time." : "ઝિગઝેગ પરિપૂર્ણ બસો આ સમયે ઉપલબ્ધ નથી.",
      "Sort By-" : "દ્વારા સૉર્ટ કરો-",
      "Departure Time" : "પ્રસ્થાન સમય",
      "Arrival Time" : "આગમન સમય",
      "Bus Type" : "બસનો પ્રકાર",
      "Bus Facilities" : "બસ સુવિધાઓ",
      "Bus Operator" : "બસ ઓપરેટર",
      "To" : "પ્રતિ",
      "From" : "થી",
    },
    'sp_SPANISH': {
      "Cancel Booking" : "Cancelar reserva",
      "Select Reason" : "Seleccionar motivo",
      "Please select the reasone for cancellation:" : "Por favor seleccione el motivo de la cancelación:",
      "Please enter the different Boarding & Drop Point" : "Por favor ingresa los diferentes puntos de embarque y desembarque",
      "No booking found" : "No se encontró ninguna reserva",
      "You don't have any cancel booking records!" : "¡No tienes ningún registro de cancelación de reserva!",
      "You don't have any booking records!" : "¡No tienes ningún registro de reserva!",
      "You don't have any previous records!" : "¡No tienes ningún registro previo!",
      "Review" : "Revisar",
      "Download App" : "Descargar aplicación",
      "Language" : "Idioma",
      "Account Number" : "Número de cuenta",
      "Back" : "Atrás",
      "Amenities" : "Comodidades",
      "Seamless Travel Simplified" : "Viajes sin interrupciones simplificados",
      "Recent Booking" : "Reserva reciente",
      "PROCEED" : "PROCEDER",
      "No Coupon Available!" : "¡No hay cupón disponible!",
      "Overview" : "Descripción general",
      "Quick links" : "Enlaces rápidos",
      "Utilitises" : "Utilidades",
      "Blog" : "Blog",
      "Style guide" : "Guía de estilo",
      "Company" : "Compañía",
      "Contact" : "Contacto",
      "Licensing" : "Licencia",
      "Pricing" : "Precios",
      "Changelog" : "Registro de cambios",
      "Subcribe to our newsletter" : "Suscríbete a nuestro boletín",
      "Enter youe Email" : "Ingrese su correo electrónico",
      "Refer and Earn" : "Refiera y gane",
      "Sign Up on Zigzag" : "Regístrate en Zigzag",
      "Go Home" : "Vete a casa",
      "Ticket ID" : "Identificación de entradas",
      "Please enter the amount less then 10." : "Por favor ingrese la cantidad menor a 10.",
      "Rafer a Friend" : "Refiera un amigo",
      "Earn" : "Ganar",
      "for each friend you refer" : "por cada amigo que refieras",
      "Price - Low to high" : "Precios de barato a caro",
      "Best rated first" : "Mejor valorado primero",
      "Early departure" : "Salida anticipada",
      "Late departure" : "Salida tardía",
      "NONAC" : "NONC",
      "Sleeper" : "Durmiente",
      "Seater" : "Plazas",
      "Booked" : "Reservado",
      "Female Booked" : "Mujer Reservada",
      "Selected" : "Seleccionado",
      "Empty" : "Vacío",
      "Drop Point" : "Punto de entrega",
      "Email Id" : "Identificación de correo",
      "Enter Your Name" : "Introduzca su nombre",
      "Enter Age" : "Ingrese la edad",
      "Enter Full Name" : "Ingrese el nombre completo",
      "Total Payment" : "Pago total",
      "Booking Confirmed!" : "¡Reserva confirmada!",
      "Home" : "Hogar",
      "My Wallet" : "Mi billetera",
      "My Earning" : "mis ganancias",
      "Wallet" : "Billetera",
      "TOTAL EARNING BALANCE" : "SALDO TOTAL DE GANANCIAS",
      "Withdraw" : "Retirar",
      "Transaction Details" : "Detalles de la transacción",
      "Payout Id" : "ID de pago",
      "Amount" : "Cantidad",
      "Pay by" : "Pagado por",
      "Request Date" : "Fecha de solicitud",
      "Payout Request" : "Solicitud de pago",
      "Minimum amount" : "Monto minimo",
      "Enter Amount" : "Ingrese el monto",
      "Select Type" : "Seleccione tipo",
      "Bank Name" : "Nombre del banco",
      "Account Holder Name" : "nombre del titular de la cuenta",
      "Cancel" : "Cancelar",
      "Proceed" : "Proceder",
      "Enjoy the travel experience with us" : "Disfruta la experiencia de viajar con nosotros",
      "Book your adventure, pack your bags and let the exploration begin." : "Reserva tu aventura, haz las maletas y deja que comience la exploración.",
      "Online Bus Ticket Booking" : "Reserva de billetes de autobús online",
      "Embark on a seamless travel  experience with ProZigzagBus" : "Embárquese en una experiencia  de viaje perfecta con ProZigzagBus",
      "Book Now" : "Reservar ahora",
      "My Ticket" : "Mi billete",
      "Upcoming Trips" : "Próximos viajes",
      "Completed Trips" : "Viajes completados",
      "Cancel Trips" : "Cancelar viajes",
      "Cancellation Policy" : "Política de cancelación",
      "Contact Us" : "Contáctenos",
      "Term & Condition" : "Término y condición",
      "Privacy Policy" : "política de privacidad",
      "My Profile" : "Mi perfil",
      "Phone Number" : "Número de teléfono",
      "Enter Password" : "Introducir la contraseña",
      "Enter Name" : "Ingrese su nombre",
      "Confirm" : "Confirmar",
      "From City" : "De ciudad",
      "To City" : "A la ciudad",
      "Date" : "Fecha",
      "Please enter the Boarding / Drop Point" : "Por favor ingrese el punto de embarque/desembarque",
      "Search" : "Buscar",
      "Ticket Details" : "Detalles del billete",
      "Download Ticket" : "Descargar Entrada",
      "Download Your Ticket !" : "¡Descarga tu entrada!",
      "Download PDF" : "Descargar PDF",
      "Back to Home" : "De vuelta a casa",
      "Enter your Feedback" : "Ingrese sus comentarios",
      "Non AC" : "Sin aire acondicionado",
      "AC" : "C.A.",
      "Booking Date" : "Fecha para registrarse",
      "Payment Method" : "Método de pago",
      "Transaction Id" : "ID de transacción",
      "Ticket Id" : "Identificación de entradas",
      "Passanger(S)" : "Pasajero(s)",
      "Age" : "Edad",
      "Seat" : "Asiento",
      "Contact Details" : "Detalles de contacto",
      "Driver Details" : "Detalles del conductor",
      "Bus Number" : "Número de autobús",
      "Price Details" : "Detalles del precio",
      "Price" : "Precio",
      "Tax" : "Impuesto",
      "Discount" : "Descuento",
      "Total Price" : "Precio total",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "El número de móvil, el nombre y el número de autobús del conductor se presentarán una hora antes de la hora de salida programada.",
      "TOTAL WALLET BALANCE" : "SALDO TOTAL DEL BILLETERO",
      "Top Up" : "Completar",
      "Enter Wallet Amount" : "Ingrese el monto de la billetera",
      "Select Payment Method" : "Seleccione método de pago",
      "Continue" : "Continuar",
      "Top up" : "Completar",
      "Successfuly" : "Con éxito",
      "has been added to your wallet" : "ha sido agregado a tu billetera",
      "Done For Now" : "Hecho por ahora",
      "Another Top Up" : "Otra recarga",
      "Change Password" : "Cambiar la contraseña",
      "Enter your Mobile" : "Introduce tu móvil",
      "Next" : "Próximo",
      "Something Went Wrong!" : "¡Algo salió mal!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "¡Felicitaciones! Su billete de autobús está confirmado. Para más detalles consulta la pestaña Mi Reserva.",
      "View Transaction" : "Ver transacción",
      "Boarding Point" : "Punto de embarque",
      "Booked by Female passenger" : "Reservado por una pasajera",
      "You can not add more than" : "No puedes agregar más de",
      "passengers to a single booking with this operator" : "pasajeros a una única reserva con este operador",
      "Seats" : "Asientos",
      "Lower Seat -" : "Asiento inferior -",
      "Upper Seat -" : "Asiento superior -",
      "Procced" : "Procedido",
      "No data found!" : "¡Datos no encontrados!",
      "Lower Berth" : "Litera baja",
      "Upper Berth" : "Litera superior",
      "Personal Info" : "Información personal",
      "Dark Mode" : "Modo oscuro",
      "Term & Conditions" : "Términos y condiciones",
      "Services" : "Servicios",
      "Downloads" : "Descargas",
      "Scan Code" : "Código de escaneo",
      "Log in" : "Acceso",
      "Sign up" : "Inscribirse",
      "Logout" : "Cerrar sesión",
      "Passenger Details" : "detalles del pasajero",
      "Passanger" : "Pasajero",
      "Seat 2" : "Asiento 2",
      "Gender" : "Género",
      "Name" : "Nombre",
      "Mobile Details" : "Detalles del móvil",
      "Enter Your Mobile Number" : "Ingrese su numero celular",
      "Enter Your Email Id" : "Ingrese su identificación de correo electrónico",
      "Amount : " : "Cantidad :",
      "(Exclusive of Texes)" : "(Exclusivo de Texas)",
      "Please fill all details" : "Por favor complete todos los detalles",
      "Please select gender" : "Por favor seleccione el género",
      "Log In on Zigzag" : "Iniciar sesión en Zigzag",
      "Forgot Password" : "Has olvidado tu contraseña",
      "Don't have an account yet? " : "¿Aún no tienes una cuenta?",
      "SignUp" : "Inscribirse",
      "Something Went wrong!" : "¡Algo salió mal!",
      "Invalid Email/Mobile No or Password!!!" : "Correo electrónico/número de móvil o contraseña no válidos.",
      "Mobile or Password went wrong!" : "¡El móvil o la contraseña fallaron!",
      "Your Journey, Your Way" : "Tu viaje, a tu manera",
      "Book, Ride, Enjoy" : "Reserva, viaja, disfruta",
      "Explore, One Bus at a Time" : "Explora, un autobús a la vez",
      "Customize your travel effortlessly." : "Personaliza tu viaje sin esfuerzo.",
      "Easy booking and boarding for a stress-free journey." : "Reserva y embarque sencillos para un viaje sin estrés.",
      "Swift booking and delightful bus rides." : "Reservas rápidas y deliciosos viajes en autobús.",
      "Discover new places, one bus ride after another." : "Descubre nuevos lugares, un viaje en autobús tras otro.",
      "Qr Code" : "Código QR",
      "Tansaction Details" : "Detalles de la transacción",
      "Full Name" : "Nombre completo",
      "Email" : "Correo electrónico",
      "Search Bus" : "Buscar autobús",
      "Fill Details" : "Detalles de relleno",
      "Payment & Other Details" : "Pago y otros detalles",
      "Apply Coupon" : "Aplicar cupón",
      "Coupon Applied!" : "¡Cupón aplicado!",
      "Remove" : "Eliminar",
      "Pay from Wallet" : "Pagar desde Wallet",
      "Total Pay:-" : "Pago total: -",
      "Valid Until" : "Válido hasta",
      "Min Amount" : "Cantidad mínima",
      "Apply" : "Aplicar",
      "User" : "Usuario",
      "Agent" : "Agente",
      "Enter your Email" : "Introduce tu correo electrónico",
      "Enter your Name" : "Introduzca su nombre",
      "Enter Referral Code (optional)" : "Ingrese el código de referencia (opcional)",
      "Sign Up" : "Inscribirse",
      "Already have an account " : "Ya tienes una cuenta",
      "Log In" : "Acceso",
      "Morning" : "Mañana",
      "Afternoon" : "Tarde",
      "Evening" : "Noche",
      "Night" : "Noche",
      "Wifi" : "Wifi",
      "Water Bottle" : "Botella de agua",
      "Charging Point" : "Punto de carga",
      "Music" : "Música",
      "Medical Kit" : "Botiquín médico",
      "Live Tracking" : "Seguimiento en vivo",
      "SEATER" : "ASIENTOS",
      "SLEEPER" : "DURMIENTE",
      "Zigzag fulfilled buses are not available at this time." : "Los autobuses en zigzag no están disponibles en este momento.",
      "Sort By-" : "Ordenar por-",
      "Departure Time" : "Hora de salida",
      "Arrival Time" : "Hora de llegada",
      "Bus Type" : "Tipo de autobús",
      "Bus Facilities" : "Instalaciones de autobuses",
      "Bus Operator" : "Operador de autobús",
      "To" : "A",
      "From" : "De",
    },
    'be_BENGALI': {
      "Cancel Booking" : "বুকিং বাতিল করুন",
      "Select Reason" : "কারণ নির্বাচন করুন",
      "Please select the reasone for cancellation:" : "বাতিল করার কারণ নির্বাচন করুন:",
      "Please enter the different Boarding & Drop Point" : "অনুগ্রহ করে বিভিন্ন বোর্ডিং এবং ড্রপ পয়েন্ট লিখুন",
      "No booking found" : "কোনো বুকিং পাওয়া যায়নি",
      "You don't have any cancel booking records!" : "আপনার কোনো বাতিল বুকিং রেকর্ড নেই!",
      "You don't have any booking records!" : "আপনার কোনো বুকিং রেকর্ড নেই!",
      "You don't have any previous records!" : "আপনার কোনো আগের রেকর্ড নেই!",
      "Review" : "পুনঃমূল্যায়ন",
      "Download App" : "অ্যাপ ডাউনলোড করুন",
      "Language" : "ভাষা",
      "Account Number" : "হিসাব নাম্বার",
      "Back" : "পেছনে",
      "Amenities" : "সুযোগ-সুবিধা",
      "Seamless Travel Simplified" : "বিরামহীন ভ্রমণ সরলীকৃত",
      "Recent Booking" : "সাম্প্রতিক বুকিং",
      "PROCEED" : "এগিয়ে যান",
      "No Coupon Available!" : "কোন কুপন উপলব্ধ!",
      "Overview" : "ওভারভিউ",
      "Quick links" : "দ্রুত লিঙ্ক",
      "Utilitises" : "ইউটিলাইটিস",
      "Blog" : "ব্লগ",
      "Style guide" : "শৈলী গাইড",
      "Company" : "প্রতিষ্ঠান",
      "Contact" : "যোগাযোগ",
      "Licensing" : "লাইসেন্সিং",
      "Pricing" : "মূল্য নির্ধারণ",
      "Changelog" : "চেঞ্জলগ",
      "Subcribe to our newsletter" : "আমাদের নিউজলেটার সাবস্ক্রাইব করুন",
      "Enter youe Email" : "আপনার ইমেইল লিখুন",
      "Refer and Earn" : "রেফার করুন এবং উপার্জন করুন",
      "Sign Up on Zigzag" : "জিগজ্যাগে সাইন আপ করুন",
      "Go Home" : "বাড়িতে যেতে",
      "Ticket ID" : "টিকিট আইডি",
      "Please enter the amount less then 10." : "অনুগ্রহ করে 10 এর কম পরিমাণ লিখুন।",
      "Rafer a Friend" : "একজন বন্ধুকে রেফার করুন",
      "Earn" : "আয় করুন",
      "for each friend you refer" : "আপনি উল্লেখ করা প্রতিটি বন্ধুর জন্য",
      "Price - Low to high" : "দাম - কম থেকে বেশি",
      "Best rated first" : "সেরা রেট প্রথম",
      "Early departure" : "তাড়াতাড়ি প্রস্থান",
      "Late departure" : "দেরী প্রস্থান",
      "NONAC" : "NONAC",
      "Sleeper" : "স্লিপার",
      "Seater" : "সিটার",
      "Booked" : "বুক করা হয়েছে",
      "Female Booked" : "মহিলা বুকড",
      "Selected" : "নির্বাচিত",
      "Empty" : "খালি",
      "Drop Point" : "ড্রপ পয়েন্ট",
      "Email Id" : "ইমেইল আইডি",
      "Enter Your Name" : "আপনার নাম প্রবেশ করুন",
      "Enter Age" : "বয়স লিখুন",
      "Enter Full Name" : "পুরো নাম লিখুন",
      "Total Payment" : "মোট পরিশোধ",
      "Booking Confirmed!" : "বুকিং নিশ্চিত!",
      "Home" : "বাড়ি",
      "My Wallet" : "আমার মানিব্যাগ",
      "My Earning" : "আমার উপার্জন",
      "Wallet" : "ওয়ালেট",
      "TOTAL EARNING BALANCE" : "মোট উপার্জন ব্যালেন্স",
      "Withdraw" : "প্রত্যাহার করুন",
      "Transaction Details" : "লেনদেন বিবরণী",
      "Payout Id" : "পেআউট আইডি",
      "Amount" : "পরিমাণ",
      "Pay by" : "দ্বারা বেতন",
      "Request Date" : "অনুরোধ তারিখ",
      "Payout Request" : "পেআউট অনুরোধ",
      "Minimum amount" : "ন্যূনতম পরিমাণ",
      "Enter Amount" : "পরিমান লিখুন",
      "Select Type" : "প্রকার নির্বাচন করুন",
      "Bank Name" : "ব্যাংকের নাম",
      "Account Holder Name" : "হিসাব দাতার নাম",
      "Cancel" : "বাতিল করুন",
      "Proceed" : "এগিয়ে যান",
      "Enjoy the travel experience with us" : "আমাদের সাথে ভ্রমণ অভিজ্ঞতা উপভোগ করুন",
      "Book your adventure, pack your bags and let the exploration begin." : "আপনার অ্যাডভেঞ্চার বুক করুন, আপনার ব্যাগ প্যাক করুন এবং অন্বেষণ শুরু করুন।",
      "Online Bus Ticket Booking" : "অনলাইন বাস টিকেট বুকিং",
      "Embark on a seamless travel  experience with ProZigzagBus" : "ProZigzagBus এর সাথে একটি  নির্বিঘ্ন ভ্রমণ অভিজ্ঞতা শুরু করুন",
      "Book Now" : "এখন বুক করুন",
      "My Ticket" : "আমার টিকিট",
      "Upcoming Trips" : "আসন্ন ট্রিপ",
      "Completed Trips" : "সম্পূর্ণ ট্রিপ",
      "Cancel Trips" : "ট্রিপ বাতিল করুন",
      "Cancellation Policy" : "বাতিলকরণ নীতি",
      "Contact Us" : "যোগাযোগ করুন",
      "Term & Condition" : "শর্তাবলী",
      "Privacy Policy" : "গোপনীয়তা নীতি",
      "My Profile" : "আমার প্রোফাইল",
      "Phone Number" : "ফোন নম্বর",
      "Enter Password" : "পাসওয়ার্ড লিখুন",
      "Enter Name" : "নাম লিখুন",
      "Confirm" : "নিশ্চিত করুন",
      "From City" : "শহর থেকে",
      "To City" : "শহরের দিকে",
      "Date" : "তারিখ",
      "Please enter the Boarding / Drop Point" : "অনুগ্রহ করে বোর্ডিং / ড্রপ পয়েন্ট লিখুন",
      "Search" : "অনুসন্ধান করুন",
      "Ticket Details" : "টিকিটের বিবরণ",
      "Download Ticket" : "টিকিট ডাউনলোড করুন",
      "Download Your Ticket !" : "আপনার টিকিট ডাউনলোড করুন!",
      "Download PDF" : "PDF ডাউনলোড করুন",
      "Back to Home" : "বাড়িতে ফিরে যাও",
      "Enter your Feedback" : "আপনার প্রতিক্রিয়া লিখুন",
      "Non AC" : "নন এসি",
      "AC" : "এসি",
      "Booking Date" : "বুকিং তারিখ",
      "Payment Method" : "মূল্যপরিশোধ পদ্ধতি",
      "Transaction Id" : "লেনদেন নাম্বার",
      "Ticket Id" : "টিকিট আইডি",
      "Passanger(S)" : "যাত্রী(গুলি)",
      "Age" : "বয়স",
      "Seat" : "আসন",
      "Contact Details" : "যোগাযোগের ঠিকানা",
      "Driver Details" : "ড্রাইভার বিবরণ",
      "Bus Number" : "বাস নম্বর",
      "Price Details" : "মূল্য বিবরণ",
      "Price" : "দাম",
      "Tax" : "ট্যাক্স",
      "Discount" : "ছাড়",
      "Total Price" : "মোট দাম",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "চালকের মোবাইল নম্বর, নাম এবং বাস নম্বর আপনার নির্ধারিত যাত্রার সময়ের এক ঘন্টা আগে উপস্থাপন করা হবে।",
      "TOTAL WALLET BALANCE" : "মোট ওয়ালেট ব্যালেন্স",
      "Top Up" : "টপ আপ",
      "Enter Wallet Amount" : "ওয়ালেট পরিমাণ লিখুন",
      "Select Payment Method" : "পেমেন্ট পদ্ধতি নির্বাচন করুন",
      "Continue" : "চালিয়ে যান",
      "Top up" : "টপ আপ",
      "Successfuly" : "সফলভাবে",
      "has been added to your wallet" : "আপনার ওয়ালেট যোগ করা হয়েছে",
      "Done For Now" : "এখন জন্য সম্পন্ন",
      "Another Top Up" : "আরেকটি টপ আপ",
      "Change Password" : "পাসওয়ার্ড পরিবর্তন করুন",
      "Enter your Mobile" : "আপনার মোবাইল লিখুন",
      "Next" : "পরবর্তী",
      "Something Went Wrong!" : "কিছু ভুল হয়েছে!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "অভিনন্দন! আপনার বাসের টিকিট নিশ্চিত হয়েছে। আরো বিস্তারিত জানার জন্য আমার বুকিং ট্যাব চেক করুন.",
      "View Transaction" : "লেনদেন দেখুন",
      "Boarding Point" : "বোর্ডিং পয়েন্ট",
      "Booked by Female passenger" : "মহিলা যাত্রী দ্বারা বুক করা",
      "You can not add more than" : "এর বেশি যোগ করতে পারবেন না",
      "passengers to a single booking with this operator" : "এই অপারেটরের সাথে একক বুকিংয়ে যাত্রীরা",
      "Seats" : "আসন",
      "Lower Seat -" : "নীচের আসন -",
      "Upper Seat -" : "উপরের সিট -",
      "Procced" : "প্রসেসড",
      "No data found!" : "কোন তথ্য পাওয়া যায়নি!",
      "Lower Berth" : "লোয়ার বার্থ",
      "Upper Berth" : "আপার বার্থ",
      "Personal Info" : "ব্যাক্তিগত তথ্য",
      "Dark Mode" : "ডার্ক মোড",
      "Term & Conditions" : "মেয়াদ ও শর্তাবলী",
      "Services" : "সেবা",
      "Downloads" : "ডাউনলোড",
      "Scan Code" : "স্ক্যান কোড",
      "Log in" : "প্রবেশ করুন",
      "Sign up" : "নিবন্ধন করুন",
      "Logout" : "প্রস্থান",
      "Passenger Details" : "যাত্রীর বিবরণ",
      "Passanger" : "যাত্রী",
      "Seat 2" : "আসন 2",
      "Gender" : "লিঙ্গ",
      "Name" : "নাম",
      "Mobile Details" : "মোবাইলের বিবরণ",
      "Enter Your Mobile Number" : "আপনার মোবাইল নাম্বার প্রবেশ করুন",
      "Enter Your Email Id" : "আপনার ইমেইল আইডি লিখুন",
      "Amount : " : "পরিমাণ:",
      "(Exclusive of Texes)" : "(টেক্সেসের একচেটিয়া)",
      "Please fill all details" : "সমস্ত বিবরণ পূরণ করুন",
      "Please select gender" : "অনুগ্রহ করে লিঙ্গ নির্বাচন করুন",
      "Log In on Zigzag" : "Zigzag এ লগ ইন করুন",
      "Forgot Password" : "পাসওয়ার্ড ভুলে গেছেন",
      "Don't have an account yet? " : "কোনো একাউন্ট এখনও আছে না?",
      "SignUp" : "নিবন্ধন করুন",
      "Something Went wrong!" : "কিছু ভুল হয়েছে!",
      "Invalid Email/Mobile No or Password!!!" : "অবৈধ ইমেল/মোবাইল নম্বর বা পাসওয়ার্ড!!!",
      "Mobile or Password went wrong!" : "মোবাইল বা পাসওয়ার্ড ভুল!",
      "Your Journey, Your Way" : "আপনার যাত্রা, আপনার পথ",
      "Book, Ride, Enjoy" : "বই, রাইড, উপভোগ করুন",
      "Explore, One Bus at a Time" : "অন্বেষণ, এক সময়ে একটি বাস",
      "Customize your travel effortlessly." : "অনায়াসে আপনার ভ্রমণ কাস্টমাইজ করুন.",
      "Easy booking and boarding for a stress-free journey." : "চাপমুক্ত যাত্রার জন্য সহজ বুকিং এবং বোর্ডিং।",
      "Swift booking and delightful bus rides." : "সুইফট বুকিং এবং আনন্দদায়ক বাস যাত্রা।",
      "Discover new places, one bus ride after another." : "নতুন জায়গা আবিষ্কার করুন, একের পর এক বাসে চড়ুন।",
      "Qr Code" : "Qr কোড",
      "Tansaction Details" : "Tansaction বিবরণ",
      "Full Name" : "পুরো নাম",
      "Email" : "ইমেইল",
      "Search Bus" : "বাস অনুসন্ধান করুন",
      "Fill Details" : "বিবরণ পূরণ করুন",
      "Payment & Other Details" : "পেমেন্ট এবং অন্যান্য বিবরণ",
      "Apply Coupon" : "কুপন প্রয়োগ করুন",
      "Coupon Applied!" : "কুপন প্রয়োগ করা হয়েছে!",
      "Remove" : "অপসারণ",
      "Pay from Wallet" : "ওয়ালেট থেকে অর্থ প্রদান করুন",
      "Total Pay:-" : "মোট বেতন:-",
      "Valid Until" : "বৈধতার সীমা",
      "Min Amount" : "ন্যূনতম পরিমাণ",
      "Apply" : "আবেদন করুন",
      "User" : "ব্যবহারকারী",
      "Agent" : "প্রতিনিধি",
      "Enter your Email" : "তুমার ইমেইল প্রবেশ করাও",
      "Enter your Name" : "আপনার নাম প্রবেশ করুন",
      "Enter Referral Code (optional)" : "রেফারেল কোড লিখুন (ঐচ্ছিক)",
      "Sign Up" : "নিবন্ধন করুন",
      "Already have an account " : "ইতিমধ্যে একটি সদস্যপদ আছে",
      "Log In" : "প্রবেশ করুন",
      "Morning" : "সকাল",
      "Afternoon" : "বিকেল",
      "Evening" : "সন্ধ্যা",
      "Night" : "রাত্রি",
      "Wifi" : "ওয়াইফাই",
      "Water Bottle" : "পানির বোতল",
      "Charging Point" : "চার্জিং পয়েন্ট",
      "Music" : "সঙ্গীত",
      "Medical Kit" : "প্রাথমিক চিকিৎসার যন্ত্রপাতি",
      "Live Tracking" : "লাইভ ট্র্যাকিং",
      "SEATER" : "সিটার",
      "SLEEPER" : "স্লিপার",
      "Zigzag fulfilled buses are not available at this time." : "জিগজ্যাগ পরিপূর্ণ বাস এই সময়ে উপলব্ধ নেই।",
      "Sort By-" : "ক্রমানুসার-",
      "Departure Time" : "ছাড়ার সময়",
      "Arrival Time" : "আগমনের সময়",
      "Bus Type" : "বাসের ধরন",
      "Bus Facilities" : "বাস সুবিধা",
      "Bus Operator" : "বাস অপারেটর",
      "To" : "প্রতি",
      "From" : "থেকে",
    },
    'id_INDONESIAN': {
      "Cancel Booking" : "Batalkan Pemesanan",
      "Select Reason" : "Pilih Alasan",
      "Please select the reasone for cancellation:" : "Silakan pilih alasan pembatalan:",
      "Please enter the different Boarding & Drop Point" : "Silakan masukkan Boarding & Drop Point yang berbeda",
      "No booking found" : "Tidak ada pemesanan yang ditemukan",
      "You don't have any cancel booking records!" : "Anda tidak memiliki catatan pembatalan pemesanan!",
      "You don't have any booking records!" : "Anda tidak memiliki catatan pemesanan apa pun!",
      "You don't have any previous records!" : "Anda tidak memiliki catatan sebelumnya!",
      "Review" : "Tinjauan",
      "Download App" : "Unduh Aplikasi",
      "Language" : "Bahasa",
      "Account Number" : "Nomor akun",
      "Back" : "Kembali",
      "Amenities" : "Fasilitas",
      "Seamless Travel Simplified" : "Perjalanan Mulus Disederhanakan",
      "Recent Booking" : "Pemesanan Terbaru",
      "PROCEED" : "MELANJUTKAN",
      "No Coupon Available!" : "Tidak Ada Kupon Tersedia!",
      "Overview" : "Ringkasan",
      "Quick links" : "Tautan langsung",
      "Utilitises" : "kegunaan",
      "Blog" : "Blog",
      "Style guide" : "Panduan gaya",
      "Company" : "Perusahaan",
      "Contact" : "Kontak",
      "Licensing" : "Perizinan",
      "Pricing" : "Harga",
      "Changelog" : "log perubahan",
      "Subcribe to our newsletter" : "Berlangganan buletin kami",
      "Enter youe Email" : "Masukkan Email Anda",
      "Refer and Earn" : "Rujuk dan Dapatkan",
      "Sign Up on Zigzag" : "Mendaftar di Zigzag",
      "Go Home" : "Pulang ke rumah",
      "Ticket ID" : "ID tiket",
      "Please enter the amount less then 10." : "Silakan masukkan jumlahnya kurang dari 10.",
      "Rafer a Friend" : "Rafer seorang Teman",
      "Earn" : "Menghasilkan",
      "for each friend you refer" : "untuk setiap teman yang Anda referensikan",
      "Price - Low to high" : "Harga - Rendah ke tinggi",
      "Best rated first" : "Peringkat terbaik pertama",
      "Early departure" : "Keberangkatan awal",
      "Late departure" : "Keberangkatan terlambat",
      "NONAC" : "NONAC",
      "Sleeper" : "Tidur",
      "Seater" : "tempat duduk",
      "Booked" : "Dipesan",
      "Female Booked" : "Wanita Dipesan",
      "Selected" : "Terpilih",
      "Empty" : "Kosong",
      "Drop Point" : "Titik Jatuh",
      "Email Id" : "nomor email",
      "Enter Your Name" : "Masukkan nama Anda",
      "Enter Age" : "Masukkan Usia",
      "Enter Full Name" : "Masukkan Nama Lengkap",
      "Total Payment" : "Total pembayaran",
      "Booking Confirmed!" : "Pemesanan Dikonfirmasi!",
      "Home" : "Rumah",
      "My Wallet" : "Dompetku",
      "My Earning" : "Penghasilan saya",
      "Wallet" : "Dompet",
      "TOTAL EARNING BALANCE" : "TOTAL SALDO PENDAPATAN",
      "Withdraw" : "Menarik",
      "Transaction Details" : "Detil transaksi",
      "Payout Id" : "Id Pembayaran",
      "Amount" : "Jumlah",
      "Pay by" : "Membayar dengan",
      "Request Date" : "Tanggal Permintaan",
      "Payout Request" : "Permintaan Pembayaran",
      "Minimum amount" : "Jumlah minimal",
      "Enter Amount" : "Masukan jumlah",
      "Select Type" : "Pilih tipe",
      "Bank Name" : "Nama Bank",
      "Account Holder Name" : "nama pemilik akun",
      "Cancel" : "Membatalkan",
      "Proceed" : "Melanjutkan",
      "Enjoy the travel experience with us" : "Nikmati pengalaman perjalanan bersama kami",
      "Book your adventure, pack your bags and let the exploration begin." : "Pesan petualangan Anda, kemasi tas Anda, dan biarkan penjelajahan dimulai.",
      "Online Bus Ticket Booking" : "Pemesanan Tiket Bus Online",
      "Embark on a seamless travel  experience with ProZigzagBus" : "Mulailah pengalaman perjalanan  yang lancar dengan ProZigzagBus",
      "Book Now" : "Pesan sekarang",
      "My Ticket" : "Tiket saya",
      "Upcoming Trips" : "Perjalanan Mendatang",
      "Completed Trips" : "Perjalanan Selesai",
      "Cancel Trips" : "Batalkan Perjalanan",
      "Cancellation Policy" : "Kebijakan Pembatalan",
      "Contact Us" : "Hubungi kami",
      "Term & Condition" : "Syarat & Ketentuan",
      "Privacy Policy" : "Kebijakan pribadi",
      "My Profile" : "Profil saya",
      "Phone Number" : "Nomor telepon",
      "Enter Password" : "Masukkan kata kunci",
      "Enter Name" : "Masukkan nama",
      "Confirm" : "Mengonfirmasi",
      "From City" : "Dari Kota",
      "To City" : "Ke Kota",
      "Date" : "Tanggal",
      "Please enter the Boarding / Drop Point" : "Silakan masukkan Boarding / Drop Point",
      "Search" : "Mencari",
      "Ticket Details" : "Detail Tiket",
      "Download Ticket" : "Unduh Tiket",
      "Download Your Ticket !" : "Unduh Tiket Anda!",
      "Download PDF" : "Unduh PDF",
      "Back to Home" : "Kembali ke rumah",
      "Enter your Feedback" : "Masukkan Masukan Anda",
      "Non AC" : "Tanpa AC",
      "AC" : "AC",
      "Booking Date" : "Tanggal Pemesanan",
      "Payment Method" : "Cara Pembayaran",
      "Transaction Id" : "ID transaksi",
      "Ticket Id" : "ID Tiket",
      "Passanger(S)" : "Penumpang",
      "Age" : "Usia",
      "Seat" : "Kursi",
      "Contact Details" : "Detail Kontak",
      "Driver Details" : "Detail pengemudi",
      "Bus Number" : "Nomor Bus",
      "Price Details" : "Detail Harga",
      "Price" : "Harga",
      "Tax" : "Pajak",
      "Discount" : "Diskon",
      "Total Price" : "Total harga",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "Nomor ponsel pengemudi, nama, dan nomor bus akan diberikan satu jam sebelum jadwal keberangkatan Anda.",
      "TOTAL WALLET BALANCE" : "TOTAL SALDO DOMPET",
      "Top Up" : "Isi Ulang",
      "Enter Wallet Amount" : "Masukkan Jumlah Dompet",
      "Select Payment Method" : "Pilih metode pembayaran",
      "Continue" : "Melanjutkan",
      "Top up" : "Isi ulang",
      "Successfuly" : "Berhasil",
      "has been added to your wallet" : "telah ditambahkan ke dompet Anda",
      "Done For Now" : "Selesai Untuk Saat Ini",
      "Another Top Up" : "Isi Ulang Lainnya",
      "Change Password" : "Ganti kata sandi",
      "Enter your Mobile" : "Masukkan Ponsel Anda",
      "Next" : "Berikutnya",
      "Something Went Wrong!" : "Ada yang salah!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "Selamat! tiket bus Anda dikonfirmasi. Untuk lebih jelasnya periksa tab Pemesanan Saya.",
      "View Transaction" : "Lihat Transaksi",
      "Boarding Point" : "Titik Keberangkatan",
      "Booked by Female passenger" : "Dipesan oleh penumpang wanita",
      "You can not add more than" : "Anda tidak dapat menambahkan lebih dari",
      "passengers to a single booking with this operator" : "penumpang untuk satu pemesanan dengan operator ini",
      "Seats" : "Tempat duduk",
      "Lower Seat -" : "Kursi Bawah -",
      "Upper Seat -" : "Kursi Atas -",
      "Procced" : "Diproses",
      "No data found!" : "Tidak ada data ditemukan!",
      "Lower Berth" : "Tempat Tidur Bawah",
      "Upper Berth" : "Tempat Tidur Atas",
      "Personal Info" : "Informasi pribadi",
      "Dark Mode" : "Mode Gelap",
      "Term & Conditions" : "Syarat & Ketentuan",
      "Services" : "Jasa",
      "Downloads" : "Unduhan",
      "Scan Code" : "Pindai Kode",
      "Log in" : "Gabung",
      "Sign up" : "Mendaftar",
      "Logout" : "Keluar",
      "Passenger Details" : "Detail Penumpang",
      "Passanger" : "Penumpang",
      "Seat 2" : "Kursi 2",
      "Gender" : "Jenis kelamin",
      "Name" : "Nama",
      "Mobile Details" : "Detail Seluler",
      "Enter Your Mobile Number" : "Masukkan nomor ponsel Anda",
      "Enter Your Email Id" : "Masukkan Id Email Anda",
      "Amount : " : "Jumlah :",
      "(Exclusive of Texes)" : "(Eksklusif dari Texas)",
      "Please fill all details" : "Silakan isi semua detailnya",
      "Please select gender" : "Silakan pilih jenis kelamin",
      "Log In on Zigzag" : "Masuk di Zigzag",
      "Forgot Password" : "Tidak ingat kata sandi",
      "Don't have an account yet? " : "Belum punya akun?",
      "SignUp" : "Mendaftar",
      "Something Went wrong!" : "Ada yang salah!",
      "Invalid Email/Mobile No or Password!!!" : "Email/Nomor Ponsel atau Kata Sandi Tidak Valid!!!",
      "Mobile or Password went wrong!" : "Ponsel atau Kata Sandi salah!",
      "Your Journey, Your Way" : "Perjalananmu, Jalanmu",
      "Book, Ride, Enjoy" : "Pesan, Naik, Nikmati",
      "Explore, One Bus at a Time" : "Jelajahi, Satu Bus Sekaligus",
      "Customize your travel effortlessly." : "Sesuaikan perjalanan Anda dengan mudah.",
      "Easy booking and boarding for a stress-free journey." : "Pemesanan dan boarding yang mudah untuk perjalanan bebas stres.",
      "Swift booking and delightful bus rides." : "Pemesanan cepat dan perjalanan bus yang menyenangkan.",
      "Discover new places, one bus ride after another." : "Temukan tempat-tempat baru, naik bus demi bus.",
      "Qr Code" : "Kode QR",
      "Tansaction Details" : "Detail Transaksi",
      "Full Name" : "Nama lengkap",
      "Email" : "Surel",
      "Search Bus" : "Cari Bus",
      "Fill Details" : "Isi Detail",
      "Payment & Other Details" : "Pembayaran & Detail Lainnya",
      "Apply Coupon" : "Terapkan Kupon",
      "Coupon Applied!" : "Kupon Berlaku!",
      "Remove" : "Menghapus",
      "Pay from Wallet" : "Bayar dari Dompet",
      "Total Pay:-" : "Total Pembayaran: -",
      "Valid Until" : "Berlaku hingga",
      "Min Amount" : "Jumlah Minimal",
      "Apply" : "Menerapkan",
      "User" : "Pengguna",
      "Agent" : "Agen",
      "Enter your Email" : "Masukkan email Anda",
      "Enter your Name" : "Masukkan nama Anda",
      "Enter Referral Code (optional)" : "Masukkan Kode Referensi (opsional)",
      "Sign Up" : "Mendaftar",
      "Already have an account " : "Sudah memiliki akun",
      "Log In" : "Gabung",
      "Morning" : "Pagi",
      "Afternoon" : "Sore",
      "Evening" : "Malam",
      "Night" : "Malam",
      "Wifi" : "Wifi",
      "Water Bottle" : "Botol air",
      "Charging Point" : "Titik Pengisian Daya",
      "Music" : "Musik",
      "Medical Kit" : "Alat medis",
      "Live Tracking" : "Pelacakan Langsung",
      "SEATER" : "tempat duduk",
      "SLEEPER" : "TIDUR",
      "Zigzag fulfilled buses are not available at this time." : "Bus yang dipenuhi Zigzag tidak tersedia saat ini.",
      "Sort By-" : "Sortir dengan-",
      "Departure Time" : "Waktu keberangkatan",
      "Arrival Time" : "Jam kedatangan",
      "Bus Type" : "Jenis Bus",
      "Bus Facilities" : "Fasilitas Bus",
      "Bus Operator" : "Operator Bus",
      "To" : "Ke",
      "From" : "Dari",
    },
    'hi_HINDI': {
      "Cancel Booking" : "बुकिंग रद्द करें",
      "Select Reason" : "कारण चुनें",
      "Please select the reasone for cancellation:" : "कृपया रद्द करने का कारण चुनें:",
      "Please enter the different Boarding & Drop Point" : "कृपया अलग-अलग बोर्डिंग और ड्रॉप प्वाइंट दर्ज करें",
      "No booking found" : "कोई बुकिंग नहीं मिली",
      "You don't have any cancel booking records!" : "आपके पास कोई रद्द बुकिंग रिकॉर्ड नहीं है!",
      "You don't have any booking records!" : "आपके पास कोई बुकिंग रिकॉर्ड नहीं है!",
      "You don't have any previous records!" : "आपके पास कोई पिछला रिकॉर्ड नहीं है!",
      "Review" : "समीक्षा",
      "Download App" : "ऐप डाउनलोड करें",
      "Language" : "भाषा",
      "Account Number" : "खाता संख्या",
      "Back" : "पीछे",
      "Amenities" : "सुविधाएं",
      "Seamless Travel Simplified" : "निर्बाध यात्रा सरलीकृत",
      "Recent Booking" : "हालिया बुकिंग",
      "PROCEED" : "आगे बढ़ना",
      "No Coupon Available!" : "कोई कूपन उपलब्ध नहीं!",
      "Overview" : "अवलोकन",
      "Quick links" : "त्वरित सम्पक",
      "Utilitises" : "उपयोगिता",
      "Blog" : "ब्लॉग",
      "Style guide" : "शैली गाइड",
      "Company" : "कंपनी",
      "Contact" : "संपर्क",
      "Licensing" : "लाइसेंसिंग",
      "Pricing" : "मूल्य निर्धारण",
      "Changelog" : "बदलाव का",
      "Subcribe to our newsletter" : "हमारे न्यूज़लेटर की सदस्यता लें",
      "Enter youe Email" : "अपना ईमेल दर्ज करें",
      "Refer and Earn" : "देखें और कमाएँ",
      "Sign Up on Zigzag" : "ज़िगज़ैग पर साइन अप करें",
      "Go Home" : "घर जाओ",
      "Ticket ID" : "टिकट आईडी",
      "Please enter the amount less then 10." : "कृपया 10 से कम राशि दर्ज करें।",
      "Rafer a Friend" : "किसी मित्र को रेफर करें",
      "Earn" : "कमाना",
      "for each friend you refer" : "आपके द्वारा संदर्भित प्रत्येक मित्र के लिए",
      "Price - Low to high" : "कीमतों का उतार - चढ़ाव",
      "Best rated first" : "सबसे पहले रेटिंग दी गई",
      "Early departure" : "जल्दी प्रस्थान",
      "Late departure" : "देर से प्रस्थान",
      "NONAC" : "NONAC",
      "Sleeper" : "स्लीपर",
      "Seater" : "सीटर",
      "Booked" : "बुक्ड",
      "Female Booked" : "महिला पर मामला दर्ज",
      "Selected" : "चयनित",
      "Empty" : "खाली",
      "Drop Point" : "ड्रॉप बिंदु",
      "Email Id" : "ईमेल आईडी",
      "Enter Your Name" : "अपना नाम दर्ज करें",
      "Enter Age" : "आयु दर्ज करें",
      "Enter Full Name" : "पूरा नाम दर्ज करें",
      "Total Payment" : "कुल भुगतान",
      "Booking Confirmed!" : "बुकिंग संपुष्ट!",
      "Home" : "घर",
      "My Wallet" : "मेरा बटुआ",
      "My Earning" : "मेरी कमाई",
      "Wallet" : "बटुआ",
      "TOTAL EARNING BALANCE" : "कुल कमाई शेष",
      "Withdraw" : "निकालना",
      "Transaction Details" : "लेनदेन का विवरण",
      "Payout Id" : "भुगतान आईडी",
      "Amount" : "मात्रा",
      "Pay by" : "द्वारा भुगतान",
      "Request Date" : "अनुरोध की तिथि",
      "Payout Request" : "भुगतान अनुरोध",
      "Minimum amount" : "न्यूनतम राशि",
      "Enter Amount" : "राशि डालें",
      "Select Type" : "प्रकार चुनें",
      "Bank Name" : "बैंक का नाम",
      "Account Holder Name" : "खाता धारक का नाम",
      "Cancel" : "रद्द करना",
      "Proceed" : "आगे बढ़ना",
      "Enjoy the travel experience with us" : "हमारे साथ यात्रा अनुभव का आनंद लें",
      "Book your adventure, pack your bags and let the exploration begin." : "अपना साहसिक कार्य बुक करें, अपने बैग पैक करें और अन्वेषण शुरू करें।",
      "Online Bus Ticket Booking" : "ऑनलाइन बस टिकट बुकिंग",
      "Embark on a seamless travel  experience with ProZigzagBus" : "ProZigzagBus के साथ एक  सहज यात्रा अनुभव शुरू करें",
      "Book Now" : "अभी बुक करें",
      "My Ticket" : "मेरा टिकट",
      "Upcoming Trips" : "आगामी यात्राएँ",
      "Completed Trips" : "यात्राएँ पूरी कीं",
      "Cancel Trips" : "यात्राएं रद्द करें",
      "Cancellation Policy" : "रद्द करने की नीति",
      "Contact Us" : "संपर्क करें",
      "Term & Condition" : "अवधि और हालत",
      "Privacy Policy" : "गोपनीयता नीति",
      "My Profile" : "मेरी प्रोफाइल",
      "Phone Number" : "फ़ोन नंबर",
      "Enter Password" : "पास वर्ड दर्ज करें",
      "Enter Name" : "नाम दर्ज करें",
      "Confirm" : "पुष्टि करना",
      "From City" : "शहर से",
      "To City" : "शहर के लिए",
      "Date" : "तारीख",
      "Please enter the Boarding / Drop Point" : "कृपया बोर्डिंग/ड्रॉप पॉइंट दर्ज करें",
      "Search" : "खोज",
      "Ticket Details" : "टिकट विवरण",
      "Download Ticket" : "टिकट डाउनलोड करें",
      "Download Your Ticket !" : "अपना टिकट डाउनलोड करें!",
      "Download PDF" : "डाउनलोड पीडीऍफ़",
      "Back to Home" : "घर वापिस जा रहा हूँ",
      "Enter your Feedback" : "अपनी प्रतिक्रिया दर्ज करें",
      "Non AC" : "नॉन एसी",
      "AC" : "एसी",
      "Booking Date" : "बुक करने की तिथि",
      "Payment Method" : "भुगतान विधि",
      "Transaction Id" : "लेनदेन आईडी",
      "Ticket Id" : "टिकट आईडी",
      "Passanger(S)" : "यात्री(एस)",
      "Age" : "आयु",
      "Seat" : "सीट",
      "Contact Details" : "सम्पर्क करने का विवरण",
      "Driver Details" : "ड्राइवर का विवरण",
      "Bus Number" : "बस नंबर",
      "Price Details" : "मूल्य विवरण",
      "Price" : "कीमत",
      "Tax" : "कर",
      "Discount" : "छूट",
      "Total Price" : "कुल कीमत",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "ड्राइवर का मोबाइल नंबर, नाम और बस नंबर आपके निर्धारित प्रस्थान समय से एक घंटे पहले प्रस्तुत किया जाएगा।",
      "TOTAL WALLET BALANCE" : "कुल वॉलेट शेष",
      "Top Up" : "लबालब भरना",
      "Enter Wallet Amount" : "वॉलेट राशि दर्ज करें",
      "Select Payment Method" : "भुगतान का तरीका चुनें",
      "Continue" : "जारी रखना",
      "Top up" : "लबालब भरना",
      "Successfuly" : "सफलतापूर्वक",
      "has been added to your wallet" : "आपके बटुए में जोड़ दिया गया है",
      "Done For Now" : "अभी के लिए हो गया",
      "Another Top Up" : "एक और टॉप अप",
      "Change Password" : "पासवर्ड बदलें",
      "Enter your Mobile" : "अपना मोबाइल डालें",
      "Next" : "अगला",
      "Something Went Wrong!" : "कुछ गलत हो गया!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "बधाई हो! आपका बस टिकट कन्फर्म हो गया है. अधिक जानकारी के लिए माई बुकिंग टैब देखें।",
      "View Transaction" : "लेन-देन देखें",
      "Boarding Point" : "बोर्डिंग प्वाइंट",
      "Booked by Female passenger" : "महिला यात्री द्वारा बुक किया गया",
      "You can not add more than" : "आप इससे अधिक नहीं जोड़ सकते",
      "passengers to a single booking with this operator" : "इस ऑपरेटर के साथ यात्रियों को एकल बुकिंग",
      "Seats" : "सीटें",
      "Lower Seat -" : "निचली सीट -",
      "Upper Seat -" : "ऊपरी सीट -",
      "Procced" : "आगे बढ़े",
      "No data found!" : "डाटा प्राप्त नहीं हुआ!",
      "Lower Berth" : "निचली शायिका",
      "Upper Berth" : "ऊपर की शैय्या",
      "Personal Info" : "व्यक्तिगत जानकारी",
      "Dark Mode" : "डार्क मोड",
      "Term & Conditions" : "नियम एवं शर्तें",
      "Services" : "सेवाएं",
      "Downloads" : "डाउनलोड",
      "Scan Code" : "कोड स्कैन करें",
      "Log in" : "लॉग इन करें",
      "Sign up" : "साइन अप करें",
      "Logout" : "लॉग आउट",
      "Passenger Details" : "यात्री विवरण",
      "Passanger" : "यात्री",
      "Seat 2" : "सीट 2",
      "Gender" : "लिंग",
      "Name" : "नाम",
      "Mobile Details" : "मोबाइल विवरण",
      "Enter Your Mobile Number" : "अपना मोबाइल संख्या दर्ज करे",
      "Enter Your Email Id" : "अपना ईमेल आईडी दर्ज करें",
      "Amount : " : "मात्रा :",
      "(Exclusive of Texes)" : "(टेक्सस को छोड़कर)",
      "Please fill all details" : "कृपया सभी विवरण भरें",
      "Please select gender" : "कृपया लिंग चुनें",
      "Log In on Zigzag" : "ज़िगज़ैग पर लॉग इन करें",
      "Forgot Password" : "पासवर्ड भूल गए",
      "Don't have an account yet? " : "अब तक कोई खाता नहीं है?",
      "SignUp" : "साइन अप करें",
      "Something Went wrong!" : "कुछ गलत हो गया!",
      "Invalid Email/Mobile No or Password!!!" : "अमान्य ईमेल/मोबाइल नंबर या पासवर्ड!!!",
      "Mobile or Password went wrong!" : "मोबाइल या पासवर्ड गलत हो गया!",
      "Your Journey, Your Way" : "आपकी यात्रा, आपका रास्ता",
      "Book, Ride, Enjoy" : "बुक करें, घूमें, आनंद लें",
      "Explore, One Bus at a Time" : "अन्वेषण करें, एक समय में एक बस",
      "Customize your travel effortlessly." : "अपनी यात्रा को सहजता से अनुकूलित करें।",
      "Easy booking and boarding for a stress-free journey." : "तनाव मुक्त यात्रा के लिए आसान बुकिंग और बोर्डिंग।",
      "Swift booking and delightful bus rides." : "त्वरित बुकिंग और आनंददायक बस यात्राएँ।",
      "Discover new places, one bus ride after another." : "नई जगहों की खोज करें, एक के बाद एक बस यात्राएँ।",
      "Qr Code" : "क्यू आर संहिता",
      "Tansaction Details" : "टैन्सैक्शन विवरण",
      "Full Name" : "पूरा नाम",
      "Email" : "ईमेल",
      "Search Bus" : "बस खोजें",
      "Fill Details" : "विवरण भरें",
      "Payment & Other Details" : "भुगतान एवं अन्य विवरण",
      "Apply Coupon" : "कूपन के लिए आवेदन करो",
      "Coupon Applied!" : "कूपन लागू!",
      "Remove" : "निकालना",
      "Pay from Wallet" : "वॉलेट से भुगतान करें",
      "Total Pay:-" : "कुल वेतन:-",
      "Valid Until" : "तब तक वैध",
      "Min Amount" : "न्यूनतम राशि",
      "Apply" : "आवेदन करना",
      "User" : "उपयोगकर्ता",
      "Agent" : "प्रतिनिधि",
      "Enter your Email" : "अपना ईमेल दर्ज करें",
      "Enter your Name" : "अपना नाम दर्ज करें",
      "Enter Referral Code (optional)" : "रेफरल कोड दर्ज करें (वैकल्पिक)",
      "Sign Up" : "साइन अप करें",
      "Already have an account " : "क्या आपके पास पहले से एक खाता मौजूद है",
      "Log In" : "लॉग इन करें",
      "Morning" : "सुबह",
      "Afternoon" : "दोपहर",
      "Evening" : "शाम",
      "Night" : "रात",
      "Wifi" : "वाईफ़ाई",
      "Water Bottle" : "पानी की बोतल",
      "Charging Point" : "चार्जिंग पॉइंट",
      "Music" : "संगीत",
      "Medical Kit" : "चिकित्सा किट",
      "Live Tracking" : "लाइव ट्रैकिंग",
      "SEATER" : "सीटर",
      "SLEEPER" : "स्लीपर",
      "Zigzag fulfilled buses are not available at this time." : "ज़िगज़ैग पूर्ण बसें इस समय उपलब्ध नहीं हैं।",
      "Sort By-" : "इसके अनुसार क्रमबद्ध करें-",
      "Departure Time" : "प्रस्थान समय",
      "Arrival Time" : "आगमन का समय",
      "Bus Type" : "बस का प्रकार",
      "Bus Facilities" : "बस सुविधाएं",
      "Bus Operator" : "बस ऑपरेटर",
      "To" : "को",
      "From" : "से",
    },
    'af_AFRIKAAN': {
      "Cancel Booking" : "Kanselleer bespreking",
      "Select Reason" : "Kies Rede",
      "Please select the reasone for cancellation:" : "Kies asseblief die rede vir kansellasie:",
      "'Please enter the different Boarding & Drop Point" : "Voer asseblief die verskillende Instap- en Aflaaipunt in",
      "No booking found" : "Geen bespreking gevind nie",
      "You don't have any cancel booking records!" : "Jy het geen kanselleerbesprekingsrekords nie!",
      "You don't have any booking records!" : "Jy het geen besprekingsrekords nie!",
      "You don't have any previous records!" : "Jy het geen vorige rekords nie!",
      "Review" : "Resensie",
      "Download App" : "Laai App af",
      "Language" : "Taal",
      "Account Number" : "Rekening nommer",
      "Back" : "Terug",
      "Amenities" : "Geriewe",
      "Seamless Travel Simplified" : "Naatlose reis vereenvoudig",
      "Recent Booking" : "Onlangse bespreking",
      "PROCEED" : "VOORTGAAN",
      "No Coupon Available!" : "Geen koepon beskikbaar nie!",
      "Overview" : "Oorsig",
      "Quick links" : "Blitsskakels",
      "Utilitises" : "Gebruike",
      "Blog" : "Blog",
      "Style guide" : "Stylgids",
      "Company" : "Maatskappy",
      "Contact" : "Kontak",
      "Licensing" : "Lisensiëring",
      "Pricing" : "Pryse",
      "Changelog" : "Veranderlogboek",
      "Subcribe to our newsletter" : "Teken in op ons nuusbrief",
      "Enter youe Email" : "Voer jou e-pos in",
      "Refer and Earn" : "Verwys en verdien",
      "Sign Up on Zigzag" : "Teken in op Zigzag",
      "Go Home" : "Gaan huis toe",
      "Ticket ID" : "Kaartjie ID",
      "Please enter the amount less then 10." : "Voer asseblief die bedrag minder as 10 in.",
      "Rafer a Friend" : "Rafer 'n vriend",
      "Earn" : "Verdien",
      "for each friend you refer" : "vir elke vriend wat jy verwys",
      "Price - Low to high" : "Prys - Laag tot hoog",
      "Best rated first" : "Beste gegradeerde eerste",
      "Early departure" : "Vroeë vertrek",
      "Late departure" : "Laat vertrek",
      "NONAC" : "NONAC",
      "Sleeper" : "Slaper",
      "Seater" : "Sitplek",
      "Booked" : "Bespreek",
      "Female Booked" : "Vrou Bespreek",
      "Selected" : "Gekies",
      "Empty" : "Leeg",
      "Drop Point" : "Drop Point",
      "Email Id" : "E-pos identiteit",
      "Enter Your Name" : "Gee jou naam",
      "Enter Age" : "Voer ouderdom in",
      "Enter Full Name" : "Voer volle naam in",
      "Total Payment" : "Totale betaling",
      "Booking Confirmed!" : "Bespreking bevestig!",
      "Home" : "Tuis",
      "My Wallet" : "My beursie",
      "My Earning" : "My verdienste",
      "Wallet" : "Beursie",
      "TOTAL EARNING BALANCE" : "TOTALE VERDIENSSALDO",
      "Withdraw" : "Onttrek",
      "Transaction Details" : "Transaksiebesonderhede",
      "Payout Id" : "Uitbetaling ID",
      "Amount" : "Bedrag",
      "Pay by" : "Betaal deur",
      "Request Date" : "versoekdatum",
      "Payout Request" : "Uitbetaling Versoek",
      "Minimum amount" : "Minimum bedrag",
      "Enter Amount" : "Voer Bedrag in",
      "Select Type" : "Kies Tipe",
      "Bank Name" : "Bank Naam",
      "Account Holder Name" : "rekeninghouer se naam",
      "Cancel" : "Kanselleer",
      "Proceed" : "Voortgaan",
      "Enjoy the travel experience with us" : "Geniet die reiservaring saam met ons",
      "Book your adventure, pack your bags and let the exploration begin." : "Bespreek jou avontuur, pak jou tasse en laat die verkenning begin.",
      "Online Bus Ticket Booking" : "Aanlyn buskaartjiebespreking",
      "Embark on a seamless travel  experience with ProZigzagBus" : "Begin 'n naatlose  reiservaring met ProZigzagBus",
      "Book Now" : "Bespreek nou",
      "My Ticket" : "My Kaartjie",
      "Upcoming Trips" : "Komende reise",
      "Completed Trips" : "Voltooide reise",
      "Cancel Trips" : "Kanselleer reise",
      "Cancellation Policy" : "Kansellasie beleid",
      "Contact Us" : "Kontak Ons",
      "Term & Condition" : "Terme & Toestand",
      "Privacy Policy" : "Privaatheidsbeleid",
      "My Profile" : "My profiel",
      "Phone Number" : "Telefoon nommer",
      "Enter Password" : "Sleutel wagwoord in",
      "Enter Name" : "Voer Naam in",
      "Confirm" : "Bevestig",
      "From City" : "Van Stad",
      "To City" : "Stad toe",
      "Date" : "Datum",
      "Please enter the Boarding / Drop Point" : "Voer asseblief die Instap-/aflaaipunt in",
      "Search" : "Soek",
      "Ticket Details" : "Kaartjiebesonderhede",
      "Download Ticket" : "Laai Kaartjie af",
      "Download Your Ticket !" : "Laai jou kaartjie af!",
      "Download PDF" : "Laai PDF af",
      "Back to Home" : "Terug huistoe",
      "Enter your Feedback" : "Voer jou terugvoer in",
      "Non AC" : "Nie AC",
      "AC" : "AC",
      "Booking Date" : "Besprekingsdatum",
      "Payment Method" : "Betalings metode",
      "Transaction Id" : "Transaksie ID",
      "Ticket Id" : "Kaartjie-ID",
      "Passanger(S)" : "Passasier(S)",
      "Age" : "Ouderdom",
      "Seat" : "Sitplek",
      "Contact Details" : "Kontakbesonderhede",
      "Driver Details" : "Bestuurder besonderhede",
      "Bus Number" : "Busnommer",
      "Price Details" : "Prys besonderhede",
      "Price" : "Prys",
      "Tax" : "Belasting",
      "Discount" : "Afslag",
      "Total Price" : "Totale prys",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "Die bestuurder se selfoonnommer, naam en busnommer sal een uur voor jou geskeduleerde vertrektyd aangebied word.",
      "TOTAL WALLET BALANCE" : "TOTALE PORTEFEUILLE BALANS",
      "Top Up" : "Vul aan",
      "Enter Wallet Amount" : "Voer beursiebedrag in",
      "Select Payment Method" : "Kies Betaalmetode",
      "Continue" : "Aanhou",
      "Top up" : "Vul aan",
      "Successfuly" : "Suksesvol",
      "has been added to your wallet" : "is by jou beursie gevoeg",
      "Done For Now" : "Vir Nou klaar",
      "Another Top Up" : "Nog 'n Top Up",
      "Change Password" : "Verander wagwoord",
      "Enter your Mobile" : "Voer jou selfoon in",
      "Next" : "Volgende",
      "Something Went Wrong!" : "Iets het verkeerd geloop!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "Baie geluk! jou buskaartjie is bevestig. Vir meer besonderhede, kyk na die My bespreking-oortjie.",
      "View Transaction" : "Bekyk transaksie",
      "Boarding Point" : "Instappunt",
      "Booked by Female passenger" : "Bespreek deur Vroulike passasier",
      "You can not add more than" : "Jy kan nie meer as byvoeg nie",
      "passengers to a single booking with this operator" : "passasiers na 'n enkele bespreking by hierdie operateur",
      "Seats" : "Sitplekke",
      "Lower Seat -" : "Onderste sitplek -",
      "Upper Seat -" : "Boonste sitplek -",
      "Procced" : "Vervolg",
      "No data found!" : "Geen data gevind nie!",
      "Lower Berth" : "Onderste bed",
      "Upper Berth" : "Boonste Kooi",
      "Personal Info" : "Persoonlike inligting",
      "Dark Mode" : "Donker modus",
      "Term & Conditions" : "Terme & Voorwaardes",
      "Services" : "Dienste",
      "Downloads" : "Aflaaie",
      "Scan Code" : "Skandeer kode",
      "Log in" : "Teken aan",
      "Sign up" : "Teken aan",
      "Logout" : "Teken uit",
      "Passenger Details" : "Passasierbesonderhede",
      "Passanger" : "Passasier",
      "Seat 2" : "Sitplek 2",
      "Gender" : "Geslag",
      "Name" : "Naam",
      "Mobile Details" : "Mobiele besonderhede",
      "Enter Your Mobile Number" : "Voer jou selfoonnommer in",
      "Enter Your Email Id" : "Voer jou e-pos-ID in",
      "Amount : " : "Bedrag:",
      "(Exclusive of Texes)" : "(Eksklusief Texes)",
      "Please fill all details" : "Vul asseblief alle besonderhede in",
      "Please select gender" : "Kies asseblief geslag",
      "Log In on Zigzag" : "Teken in op Zigzag",
      "Forgot Password" : "Wagwoord vergeet",
      "Don't have an account yet? " : "Het jy nog nie 'n rekening nie?",
      "SignUp" : "Teken aan",
      "Something Went wrong!" : "Iets het verkeerd geloop!",
      "Invalid Email/Mobile No or Password!!!" : "Ongeldige e-pos-/selfoonnommer of wagwoord!!!",
      "Mobile or Password went wrong!" : "Selfoon of wagwoord het verkeerd geloop!",
      "Your Journey, Your Way" : "Jou Reis, Jou Weg",
      "Book, Ride, Enjoy" : "Bespreek, ry, geniet",
      "Explore, One Bus at a Time" : "Verken, een bus op 'n slag",
      "Customize your travel effortlessly." : "Pas jou reis moeiteloos aan.",
      "Easy booking and boarding for a stress-free journey." : "Maklike bespreking en instap vir 'n stresvrye reis.",
      "Swift booking and delightful bus rides." : "Vinnige bespreking en heerlike busritte.",
      "Discover new places, one bus ride after another." : "Ontdek nuwe plekke, een busrit na die ander.",
      "Qr Code" : "QR kode",
      "Tansaction Details" : "Tansaksie Besonderhede",
      "Full Name" : "Volle naam",
      "Email" : "E-pos",
      "Search Bus" : "Soek Bus",
      "Fill Details" : "Vul Besonderhede in",
      "Payment & Other Details" : "Betaling en ander besonderhede",
      "Apply Coupon" : "Pas koepon toe",
      "Coupon Applied!" : "Koepon toegepas!",
      "Remove" : "Verwyder",
      "Pay from Wallet" : "Betaal uit Wallet",
      "Total Pay:-" : "Totale betaling:-",
      "Valid Until" : "Geldig tot",
      "Min Amount" : "Min hoeveelheid",
      "Apply" : "Doen aansoek",
      "User" : "Gebruiker",
      "Agent" : "Agent",
      "Enter your Email" : "Gee jou e-pos",
      "Enter your Name" : "Gee jou naam",
      "Enter Referral Code (optional)" : "Voer verwysingskode in (opsioneel)",
      "Sign Up" : "Teken aan",
      "Already have an account " : "Reeds 'n rekening",
      "Log In" : "Teken aan",
      "Morning" : "Oggend",
      "Afternoon" : "Middag",
      "Evening" : "Aand",
      "Night" : "Nag",
      "Wifi" : "Wifi",
      "Water Bottle" : "Waterbottel",
      "Charging Point" : "Laaipunt",
      "Music" : "Musiek",
      "Medical Kit" : "Mediese Kit",
      "Live Tracking" : "Regstreekse dop",
      "SEATER" : "SITPLAATS",
      "SLEEPER" : "SLAAPPER",
      "Zigzag fulfilled buses are not available at this time." : "Zigzag vervulde busse is nie tans beskikbaar nie.",
      "Sort By-" : "Sorteer Volgens-",
      "Departure Time" : "Vertrektyd",
      "Arrival Time" : "Aankoms tyd",
      "Bus Type" : "Bus Tipe",
      "Bus Facilities" : "Busfasiliteite",
      "Bus Operator" : "Busoperateur",
      "To" : "Om",
      "From" : "Van",
    },
    'ar_ARABIC': {
      "Cancel Booking" : "إلغاء الحجز",
      "Select Reason" : "حدد السبب",
      "Please select the reasone for cancellation:" : "الرجاء تحديد سبب الإلغاء:",
      "Please enter the different Boarding & Drop Point" : "الرجاء إدخال نقطة الصعود والهبوط المختلفة",
      "No booking found" : "لم يتم العثور على أي حجز",
      "You don't have any cancel booking records!" : "ليس لديك أي سجلات إلغاء الحجز!",
      "You don't have any booking records!" : "ليس لديك أي سجلات حجز!",
      "You don't have any previous records!" : "ليس لديك أي سجلات سابقة!",
      "Review" : "مراجعة",
      "Download App" : "تحميل التطبيق",
      "Language" : "لغة",
      "Account Number" : "رقم حساب",
      "Back" : "خلف",
      "Amenities" : "وسائل الراحة" ,
      "Seamless Travel Simplified" : "السفر السلس والمبسط",
      "Recent Booking" : "الحجز الأخير",
      "PROCEED" : "يتابع",
      "No Coupon Available!" : "لا يوجد قسيمة متاحة!",
      "Overview" : "ملخص",
      "Quick links" : "روابط سريعة",
      "Utilitises" : "المرافق",
      "Blog" : "مدونة",
      "Style guide" : "دليل الاسلوب",
      "Company" : "شركة",
      "Contact" : "اتصال",
      "Licensing" : "الترخيص",
      "Pricing" : "التسعير",
      "Changelog" : "سجل التغيير",
      "Subcribe to our newsletter" : "اشترك في النشرة الإخبارية لدينا",
      "Enter youe Email" : "أدخل بريدك الإلكتروني",
      "Refer and Earn" : "الرجوع وكسب",
      "Sign Up on Zigzag" : "قم بالتسجيل في Zigzag",
      "Go Home" : "اذهب للمنزل",
      "Ticket ID" : "معرف التذكرة",
      "Please enter the amount less then 10." : "الرجاء إدخال المبلغ أقل من 10.",
      "Rafer a Friend" : "رافر صديق",
      "Earn" : "يكسب",
      "for each friend you refer" : "لكل صديق تشير إليه",
      "Price - Low to high" : "السعر من الارخص للاعلى",
      "Best rated first" : "الأفضل تقييمًا أولاً",
      "Early departure" : "الرحيل المبكر",
      "Late departure" : "المغادرة المتأخرة",
      "NONAC" : "نوناك",
      "Sleeper" : "النائم",
      "Seater" : "مقاعد",
      "Booked" : "حجز",
      "Female Booked" : "أنثى حجزت",
      "Selected" : "المحدد",
      "Empty" : "فارغ",
      "Drop Point" : "نقطة الإسقاط",
      "Email Id" : "عنوان الايميل",
      "Enter Your Name" : "أدخل أسمك",
      "Enter Age" : "أدخل العمر",
      "Enter Full Name" : "أدخل الاسم الكامل",
      "Total Payment" : "المبلغ الإجمالي",
      "Booking Confirmed!" : "تاكيد الحجز!",
      "Home" : "بيت",
      "My Wallet" : "محفظتى",
      "My Earning" : "كسبي",
      "Wallet" : "محفظة",
      "TOTAL EARNING BALANCE" : "إجمالي رصيد الأرباح",
      "Withdraw" : "ينسحب",
      "Transaction Details" : "تفاصيل الصفقه",
      "Payout Id" : "معرف الدفع",
      "Amount" : "كمية",
      "Pay by" : "ادفع عن طريق",
      "Request Date" : "تاريخ الطلب",
      "Payout Request" : "طلب الدفع",
      "Minimum amount" : "الحد الأدنى للمبلغ",
      "Enter Amount" : "أدخل المبلغ",
      "Select Type" : "اختر صنف",
      "Bank Name" : "اسم البنك",
      "Account Holder Name" : "اسم صاحب الحساب",
      "Cancel" : "يلغي",
      "Proceed" : "يتابع",
      "Enjoy the travel experience with us" : "استمتع بتجربة السفر معنا",
      "Book your adventure, pack your bags and let the exploration begin." : "احجز مغامرتك، واحزم حقائبك، ودع الاستكشاف يبدأ.",
      "Online Bus Ticket Booking" : "حجز تذكرة الحافلة عبر الإنترنت",
      "Embark on a seamless travel  experience with ProZigzagBus" : "انطلق في تجربة سفر  سلسة مع ProZigzagBus",
      "Book Now" : "احجز الآن",
      "My Ticket" : "تذكرتي",
      "Upcoming Trips" : "الرحلات القادمة",
      "Completed Trips" : "الرحلات المكتملة",
      "Cancel Trips" : "إلغاء الرحلات",
      "Cancellation Policy" : "سياسة الإلغاء",
      "Contact Us" : "اتصل بنا",
      "Term & Condition" : "الشروط و الأحكام",
      "Privacy Policy" : "سياسة الخصوصية",
      "My Profile" : "ملفي",
      "Phone Number" : "رقم التليفون",
      "Enter Password" : "أدخل كلمة المرور",
      "Enter Name" : "أدخل الاسم",
      "Confirm" : "يتأكد",
      "From City" : "من المدينة",
      "To City" : "إلى المدينة",
      "Date" : "تاريخ",
      "Please enter the Boarding / Drop Point" : "الرجاء إدخال نقطة الصعود/الإنزال",
      "Search" : "يبحث",
      "Ticket Details" : "تفاصيل التذكرة",
      "Download Ticket" : "تحميل تذكرة",
      "Download Your Ticket !" : "قم بتنزيل تذكرتك!",
      "Download PDF" : "تحميل PDF",
      "Back to Home" : "العودة إلى المنزل",
      "Enter your Feedback" : "أدخل ملاحظاتك",
      "Non AC" : "غير مكيف الهواء",
      "AC" : "تكييف",
      "Booking Date" : "تاريخ الحجز",
      "Payment Method" : "طريقة الدفع او السداد",
      "Transaction Id" : "رقم المعاملة",
      "Ticket Id" : "معرف التذكرة",
      "Passanger(S)" : "راكب (ص)",
      "Age" : "عمر",
      "Seat" : "مقعد",
      "Contact Details" : "بيانات المتصل",
      "Driver Details" : "تفاصيل السائق",
      "Bus Number" : "رقم الباص",
      "Price Details" : "تفاصيل الأسعار",
      "Price" : "سعر",
      "Tax" : "ضريبة",
      "Discount" : "تخفيض",
      "Total Price" : "السعر الكلي",
      "The driver's mobile number, name, and bus number will be presented one hour prior to your scheduled bus departure time." : "سيتم تقديم رقم الهاتف المحمول والاسم ورقم الحافلة للسائق قبل ساعة واحدة من موعد المغادرة المقرر.",
      "TOTAL WALLET BALANCE" : "إجمالي رصيد المحفظة",
      "Top Up" : "فوق حتى",
      "Enter Wallet Amount" : "أدخل مبلغ المحفظة",
      "Select Payment Method" : "اختار طريقة الدفع",
      "Continue" : "يكمل",
      "Top up" : "فوق حتى",
      "Successfuly" : "بنجاح",
      "has been added to your wallet" : "تمت إضافته إلى محفظتك",
      "Done For Now" : "تم الآن",
      "Another Top Up" : "تعبئة أخرى",
      "Change Password" : "تغيير كلمة المرور",
      "Enter your Mobile" : "أدخل هاتفك المحمول",
      "Next" : "التالي",
      "Something Went Wrong!" : "هناك خطأ ما!",
      "Congratulation! your bus ticket is confirmed. For more details check the My Booking tab." : "تهنئة! تم تأكيد تذكرة الحافلة الخاصة بك. لمزيد من التفاصيل، تحقق من علامة التبويب حجزي.",
      "View Transaction" : "عرض المعاملة",
      "Boarding Point" : "نقطة الصعود",
      "Booked by Female passenger" : "حجزت من قبل راكبة",
      "You can not add more than" : "لا يمكنك إضافة أكثر من",
      "passengers to a single booking with this operator" : "الركاب إلى حجز واحد مع هذا المشغل",
      "Seats" : "مقاعد",
      "Lower Seat -" : "المقعد السفلي -",
      "Upper Seat -" : "المقعد العلوي -",
      "Procced" : "تمت",
      "No data found!" : "لاتوجد بيانات!",
      "Lower Berth" : "الرصيف السفلي",
      "Upper Berth" : "السرير العلوي",
      "Personal Info" : "معلومات شخصية",
      "Dark Mode" : "الوضع المظلم",
      "Term & Conditions" : "الشروط والأحكام",
      "Services" : "خدمات",
      "Downloads" : "التحميلات",
      "Scan Code" : "رمز المسح",
      "Log in" : "تسجيل الدخول",
      "Sign up" : "اشتراك",
      "Logout" : "تسجيل خروج",
      "Passenger Details" : "تفاصيل الركاب",
      "Passanger" : "مسافر",
      "Seat 2" : "المقعد 2",
      "Gender" : "جنس",
      "Name" : "اسم",
      "Mobile Details" : "تفاصيل الجوال",
      "Enter Your Mobile Number" : "أدخل رقم هاتفك المحمول",
      "Enter Your Email Id" : "أدخل معرف البريد الإلكتروني الخاص بك",
      "Amount : " : "كمية :",
      "(Exclusive of Texes)" : "(باستثناء تكساس)",
      "Please fill all details" : "يرجى ملء كافة التفاصيل",
      "Please select gender" : "يرجى تحديد الجنس",
      "Log In on Zigzag" : "تسجيل الدخول على متعرج",
      "Forgot Password" : "هل نسيت كلمة السر",
      "Don't have an account yet? " : "لا تملك حسابا حتى الآن؟",
      "SignUp" : "اشتراك",
      "Something Went wrong!" : "هناك خطأ ما!",
      "Invalid Email/Mobile No or Password!!!" : "البريد الإلكتروني/رقم الجوال أو كلمة المرور غير صالحة!!!",
      "Mobile or Password went wrong!" : "حدث خطأ في الهاتف المحمول أو كلمة المرور!",
      "Your Journey, Your Way" : "رحلتك، طريقك",
      "Book, Ride, Enjoy" : "احجز، اركب، استمتع",
      "Explore, One Bus at a Time" : "استكشف، حافلة واحدة في كل مرة",
      "Customize your travel effortlessly." : "قم بتخصيص سفرك دون عناء.",
      "Easy booking and boarding for a stress-free journey." : "سهولة الحجز والصعود لرحلة خالية من التوتر.",
      "Swift booking and delightful bus rides." : "حجز سريع ورحلات حافلة ممتعة.",
      "Discover new places, one bus ride after another." : "اكتشف أماكن جديدة، رحلة بالحافلة تلو الأخرى.",
      "Qr Code" : "رمز الاستجابة السريعة",
      "Tansaction Details" : "تفاصيل الصفقة",
      "Full Name" : "الاسم الكامل",
      "Email" : "بريد إلكتروني",
      "Search Bus" : "ابحث عن الحافلة",
      "Fill Details" : "ملء التفاصيل",
      "Payment & Other Details" : "الدفع والتفاصيل الأخرى",
      "Apply Coupon" : "تطبيق القسيمة",
      "Coupon Applied!" : "تم تطبيق القسيمة!",
      "Remove" : "يزيل",
      "Pay from Wallet" : "الدفع من المحفظة",
      "Total Pay:-" : "إجمالي الأجر:-",
      "Valid Until" : "صالحة حتى",
      "Min Amount" : "الحد الأدنى للمبلغ",
      "Apply" : "يتقدم",
      "User" : "مستخدم",
      "Agent" : "عامل",
      "Enter your Email" : "أدخل بريدك الإلكتروني",
      "Enter your Name" : "أدخل أسمك",
      "Enter Referral Code (optional)" : "أدخل رمز الإحالة (اختياري)",
      "Sign Up" : "اشتراك",
      "Already have an account " : "هل لديك حساب",
      "Log In" : "تسجيل الدخول",
      "Morning" : "صباح",
      "Afternoon" : "بعد الظهر",
      "Evening" : "مساء",
      "Night" : "ليلة",
      "Wifi" : "واي فاي",
      "Water Bottle" : "زجاجة ماء",
      "Charging Point" : "نقطة الشحن",
      "Music" : "موسيقى",
      "Medical Kit" : "عدة طبية",
      "Live Tracking" : "تتبع مباشر",
      "SEATER" : "مقاعد",
      "SLEEPER" : "النائم",
      "Zigzag fulfilled buses are not available at this time." : "الحافلات المتعرجة غير متوفرة في هذا الوقت.",
      "Sort By-" : "ترتيب حسب-",
      "Departure Time" : "وقت المغادرة",
      "Arrival Time" : "وقت الوصول",
      "Bus Type" : "نوع الحافلة",
      "Bus Facilities" : "مرافق الحافلات",
      "Bus Operator" : "مشغل الحافلة",
      "To" : "ل",
      "From" : "من",
    }
  };
}